/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-24")
public class TLoginInfo implements org.apache.thrift.TBase<TLoginInfo, TLoginInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TLoginInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TLoginInfo");

  private static final org.apache.thrift.protocol.TField USER_AGENT_FIELD_DESC = new org.apache.thrift.protocol.TField("userAgent", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField USER_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("userIP", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LONG_SESSION_FIELD_DESC = new org.apache.thrift.protocol.TField("longSession", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TLoginInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TLoginInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String userAgent; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String userIP; // optional
  public boolean longSession; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_AGENT((short)1, "userAgent"),
    USER_IP((short)2, "userIP"),
    LONG_SESSION((short)3, "longSession");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_AGENT
          return USER_AGENT;
        case 2: // USER_IP
          return USER_IP;
        case 3: // LONG_SESSION
          return LONG_SESSION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LONGSESSION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.USER_AGENT,_Fields.USER_IP,_Fields.LONG_SESSION};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_AGENT, new org.apache.thrift.meta_data.FieldMetaData("userAgent", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USER_IP, new org.apache.thrift.meta_data.FieldMetaData("userIP", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LONG_SESSION, new org.apache.thrift.meta_data.FieldMetaData("longSession", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TLoginInfo.class, metaDataMap);
  }

  public TLoginInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TLoginInfo(TLoginInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUserAgent()) {
      this.userAgent = other.userAgent;
    }
    if (other.isSetUserIP()) {
      this.userIP = other.userIP;
    }
    this.longSession = other.longSession;
  }

  public TLoginInfo deepCopy() {
    return new TLoginInfo(this);
  }

  @Override
  public void clear() {
    this.userAgent = null;
    this.userIP = null;
    setLongSessionIsSet(false);
    this.longSession = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserAgent() {
    return this.userAgent;
  }

  public TLoginInfo setUserAgent(@org.apache.thrift.annotation.Nullable java.lang.String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  public void unsetUserAgent() {
    this.userAgent = null;
  }

  /** Returns true if field userAgent is set (has been assigned a value) and false otherwise */
  public boolean isSetUserAgent() {
    return this.userAgent != null;
  }

  public void setUserAgentIsSet(boolean value) {
    if (!value) {
      this.userAgent = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserIP() {
    return this.userIP;
  }

  public TLoginInfo setUserIP(@org.apache.thrift.annotation.Nullable java.lang.String userIP) {
    this.userIP = userIP;
    return this;
  }

  public void unsetUserIP() {
    this.userIP = null;
  }

  /** Returns true if field userIP is set (has been assigned a value) and false otherwise */
  public boolean isSetUserIP() {
    return this.userIP != null;
  }

  public void setUserIPIsSet(boolean value) {
    if (!value) {
      this.userIP = null;
    }
  }

  public boolean isLongSession() {
    return this.longSession;
  }

  public TLoginInfo setLongSession(boolean longSession) {
    this.longSession = longSession;
    setLongSessionIsSet(true);
    return this;
  }

  public void unsetLongSession() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LONGSESSION_ISSET_ID);
  }

  /** Returns true if field longSession is set (has been assigned a value) and false otherwise */
  public boolean isSetLongSession() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LONGSESSION_ISSET_ID);
  }

  public void setLongSessionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LONGSESSION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case USER_AGENT:
      if (value == null) {
        unsetUserAgent();
      } else {
        setUserAgent((java.lang.String)value);
      }
      break;

    case USER_IP:
      if (value == null) {
        unsetUserIP();
      } else {
        setUserIP((java.lang.String)value);
      }
      break;

    case LONG_SESSION:
      if (value == null) {
        unsetLongSession();
      } else {
        setLongSession((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_AGENT:
      return getUserAgent();

    case USER_IP:
      return getUserIP();

    case LONG_SESSION:
      return isLongSession();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case USER_AGENT:
      return isSetUserAgent();
    case USER_IP:
      return isSetUserIP();
    case LONG_SESSION:
      return isSetLongSession();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TLoginInfo)
      return this.equals((TLoginInfo)that);
    return false;
  }

  public boolean equals(TLoginInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_userAgent = true && this.isSetUserAgent();
    boolean that_present_userAgent = true && that.isSetUserAgent();
    if (this_present_userAgent || that_present_userAgent) {
      if (!(this_present_userAgent && that_present_userAgent))
        return false;
      if (!this.userAgent.equals(that.userAgent))
        return false;
    }

    boolean this_present_userIP = true && this.isSetUserIP();
    boolean that_present_userIP = true && that.isSetUserIP();
    if (this_present_userIP || that_present_userIP) {
      if (!(this_present_userIP && that_present_userIP))
        return false;
      if (!this.userIP.equals(that.userIP))
        return false;
    }

    boolean this_present_longSession = true && this.isSetLongSession();
    boolean that_present_longSession = true && that.isSetLongSession();
    if (this_present_longSession || that_present_longSession) {
      if (!(this_present_longSession && that_present_longSession))
        return false;
      if (this.longSession != that.longSession)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetUserAgent()) ? 131071 : 524287);
    if (isSetUserAgent())
      hashCode = hashCode * 8191 + userAgent.hashCode();

    hashCode = hashCode * 8191 + ((isSetUserIP()) ? 131071 : 524287);
    if (isSetUserIP())
      hashCode = hashCode * 8191 + userIP.hashCode();

    hashCode = hashCode * 8191 + ((isSetLongSession()) ? 131071 : 524287);
    if (isSetLongSession())
      hashCode = hashCode * 8191 + ((longSession) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TLoginInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetUserAgent()).compareTo(other.isSetUserAgent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserAgent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userAgent, other.userAgent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetUserIP()).compareTo(other.isSetUserIP());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserIP()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userIP, other.userIP);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLongSession()).compareTo(other.isSetLongSession());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongSession()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longSession, other.longSession);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TLoginInfo(");
    boolean first = true;

    if (isSetUserAgent()) {
      sb.append("userAgent:");
      if (this.userAgent == null) {
        sb.append("null");
      } else {
        sb.append(this.userAgent);
      }
      first = false;
    }
    if (isSetUserIP()) {
      if (!first) sb.append(", ");
      sb.append("userIP:");
      if (this.userIP == null) {
        sb.append("null");
      } else {
        sb.append(this.userIP);
      }
      first = false;
    }
    if (isSetLongSession()) {
      if (!first) sb.append(", ");
      sb.append("longSession:");
      sb.append(this.longSession);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TLoginInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TLoginInfoStandardScheme getScheme() {
      return new TLoginInfoStandardScheme();
    }
  }

  private static class TLoginInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TLoginInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TLoginInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_AGENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userAgent = iprot.readString();
              struct.setUserAgentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userIP = iprot.readString();
              struct.setUserIPIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LONG_SESSION
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.longSession = iprot.readBool();
              struct.setLongSessionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TLoginInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userAgent != null) {
        if (struct.isSetUserAgent()) {
          oprot.writeFieldBegin(USER_AGENT_FIELD_DESC);
          oprot.writeString(struct.userAgent);
          oprot.writeFieldEnd();
        }
      }
      if (struct.userIP != null) {
        if (struct.isSetUserIP()) {
          oprot.writeFieldBegin(USER_IP_FIELD_DESC);
          oprot.writeString(struct.userIP);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetLongSession()) {
        oprot.writeFieldBegin(LONG_SESSION_FIELD_DESC);
        oprot.writeBool(struct.longSession);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TLoginInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TLoginInfoTupleScheme getScheme() {
      return new TLoginInfoTupleScheme();
    }
  }

  private static class TLoginInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TLoginInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TLoginInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUserAgent()) {
        optionals.set(0);
      }
      if (struct.isSetUserIP()) {
        optionals.set(1);
      }
      if (struct.isSetLongSession()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetUserAgent()) {
        oprot.writeString(struct.userAgent);
      }
      if (struct.isSetUserIP()) {
        oprot.writeString(struct.userIP);
      }
      if (struct.isSetLongSession()) {
        oprot.writeBool(struct.longSession);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TLoginInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.userAgent = iprot.readString();
        struct.setUserAgentIsSet(true);
      }
      if (incoming.get(1)) {
        struct.userIP = iprot.readString();
        struct.setUserIPIsSet(true);
      }
      if (incoming.get(2)) {
        struct.longSession = iprot.readBool();
        struct.setLongSessionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

