/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-15")
public enum TUserStatus implements org.apache.thrift.TEnum {
  TUS_NULL(0),
  TUS_ACTIVE(1),
  TUS_LOCKED(2),
  TUS_REMOVED(3);

  private final int value;

  private TUserStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TUserStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return TUS_NULL;
      case 1:
        return TUS_ACTIVE;
      case 2:
        return TUS_LOCKED;
      case 3:
        return TUS_REMOVED;
      default:
        return null;
    }
  }
}
