/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-30")
public enum TBookingStatus implements org.apache.thrift.TEnum {
  TB_PENDING(1),
  TB_CONFIRMED(2),
  TB_IN_PROGRESS(3),
  TB_COMPLETED(4),
  TB_CANCELLED(5);

  private final int value;

  private TBookingStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TBookingStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return TB_PENDING;
      case 2:
        return TB_CONFIRMED;
      case 3:
        return TB_IN_PROGRESS;
      case 4:
        return TB_COMPLETED;
      case 5:
        return TB_CANCELLED;
      default:
        return null;
    }
  }
}
