/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-29")
public enum TCarStatus implements org.apache.thrift.TEnum {
  TC_ACTIVE(1),
  TC_PENDING(2),
  TC_BLOCKED(3);

  private final int value;

  private TCarStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TCarStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return TC_ACTIVE;
      case 2:
        return TC_PENDING;
      case 3:
        return TC_BLOCKED;
      default:
        return null;
    }
  }
}
