/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-10-08")
public class TCarView implements org.apache.thrift.TBase<TCarView, TCarView._Fields>, java.io.Serializable, Cloneable, Comparable<TCarView> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TCarView");

  private static final org.apache.thrift.protocol.TField CAR_FIELD_DESC = new org.apache.thrift.protocol.TField("car", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField BRAND_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("brandName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DISTRICT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("districtName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PROVINCE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("provinceName", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField OWNER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerName", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField THUMBNAIL_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("thumbnailUrl", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TCarViewStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TCarViewTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable TCar car; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String brandName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String districtName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String provinceName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String ownerName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String thumbnailUrl; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAR((short)1, "car"),
    BRAND_NAME((short)2, "brandName"),
    DISTRICT_NAME((short)3, "districtName"),
    PROVINCE_NAME((short)4, "provinceName"),
    OWNER_NAME((short)5, "ownerName"),
    THUMBNAIL_URL((short)6, "thumbnailUrl");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAR
          return CAR;
        case 2: // BRAND_NAME
          return BRAND_NAME;
        case 3: // DISTRICT_NAME
          return DISTRICT_NAME;
        case 4: // PROVINCE_NAME
          return PROVINCE_NAME;
        case 5: // OWNER_NAME
          return OWNER_NAME;
        case 6: // THUMBNAIL_URL
          return THUMBNAIL_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.BRAND_NAME,_Fields.DISTRICT_NAME,_Fields.PROVINCE_NAME,_Fields.OWNER_NAME,_Fields.THUMBNAIL_URL};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAR, new org.apache.thrift.meta_data.FieldMetaData("car", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TCar.class)));
    tmpMap.put(_Fields.BRAND_NAME, new org.apache.thrift.meta_data.FieldMetaData("brandName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISTRICT_NAME, new org.apache.thrift.meta_data.FieldMetaData("districtName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROVINCE_NAME, new org.apache.thrift.meta_data.FieldMetaData("provinceName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER_NAME, new org.apache.thrift.meta_data.FieldMetaData("ownerName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.THUMBNAIL_URL, new org.apache.thrift.meta_data.FieldMetaData("thumbnailUrl", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TCarView.class, metaDataMap);
  }

  public TCarView() {
  }

  public TCarView(
    TCar car)
  {
    this();
    this.car = car;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TCarView(TCarView other) {
    if (other.isSetCar()) {
      this.car = new TCar(other.car);
    }
    if (other.isSetBrandName()) {
      this.brandName = other.brandName;
    }
    if (other.isSetDistrictName()) {
      this.districtName = other.districtName;
    }
    if (other.isSetProvinceName()) {
      this.provinceName = other.provinceName;
    }
    if (other.isSetOwnerName()) {
      this.ownerName = other.ownerName;
    }
    if (other.isSetThumbnailUrl()) {
      this.thumbnailUrl = other.thumbnailUrl;
    }
  }

  public TCarView deepCopy() {
    return new TCarView(this);
  }

  @Override
  public void clear() {
    this.car = null;
    this.brandName = null;
    this.districtName = null;
    this.provinceName = null;
    this.ownerName = null;
    this.thumbnailUrl = null;
  }

  @org.apache.thrift.annotation.Nullable
  public TCar getCar() {
    return this.car;
  }

  public TCarView setCar(@org.apache.thrift.annotation.Nullable TCar car) {
    this.car = car;
    return this;
  }

  public void unsetCar() {
    this.car = null;
  }

  /** Returns true if field car is set (has been assigned a value) and false otherwise */
  public boolean isSetCar() {
    return this.car != null;
  }

  public void setCarIsSet(boolean value) {
    if (!value) {
      this.car = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBrandName() {
    return this.brandName;
  }

  public TCarView setBrandName(@org.apache.thrift.annotation.Nullable java.lang.String brandName) {
    this.brandName = brandName;
    return this;
  }

  public void unsetBrandName() {
    this.brandName = null;
  }

  /** Returns true if field brandName is set (has been assigned a value) and false otherwise */
  public boolean isSetBrandName() {
    return this.brandName != null;
  }

  public void setBrandNameIsSet(boolean value) {
    if (!value) {
      this.brandName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDistrictName() {
    return this.districtName;
  }

  public TCarView setDistrictName(@org.apache.thrift.annotation.Nullable java.lang.String districtName) {
    this.districtName = districtName;
    return this;
  }

  public void unsetDistrictName() {
    this.districtName = null;
  }

  /** Returns true if field districtName is set (has been assigned a value) and false otherwise */
  public boolean isSetDistrictName() {
    return this.districtName != null;
  }

  public void setDistrictNameIsSet(boolean value) {
    if (!value) {
      this.districtName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProvinceName() {
    return this.provinceName;
  }

  public TCarView setProvinceName(@org.apache.thrift.annotation.Nullable java.lang.String provinceName) {
    this.provinceName = provinceName;
    return this;
  }

  public void unsetProvinceName() {
    this.provinceName = null;
  }

  /** Returns true if field provinceName is set (has been assigned a value) and false otherwise */
  public boolean isSetProvinceName() {
    return this.provinceName != null;
  }

  public void setProvinceNameIsSet(boolean value) {
    if (!value) {
      this.provinceName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOwnerName() {
    return this.ownerName;
  }

  public TCarView setOwnerName(@org.apache.thrift.annotation.Nullable java.lang.String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

  public void unsetOwnerName() {
    this.ownerName = null;
  }

  /** Returns true if field ownerName is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerName() {
    return this.ownerName != null;
  }

  public void setOwnerNameIsSet(boolean value) {
    if (!value) {
      this.ownerName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getThumbnailUrl() {
    return this.thumbnailUrl;
  }

  public TCarView setThumbnailUrl(@org.apache.thrift.annotation.Nullable java.lang.String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
    return this;
  }

  public void unsetThumbnailUrl() {
    this.thumbnailUrl = null;
  }

  /** Returns true if field thumbnailUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetThumbnailUrl() {
    return this.thumbnailUrl != null;
  }

  public void setThumbnailUrlIsSet(boolean value) {
    if (!value) {
      this.thumbnailUrl = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CAR:
      if (value == null) {
        unsetCar();
      } else {
        setCar((TCar)value);
      }
      break;

    case BRAND_NAME:
      if (value == null) {
        unsetBrandName();
      } else {
        setBrandName((java.lang.String)value);
      }
      break;

    case DISTRICT_NAME:
      if (value == null) {
        unsetDistrictName();
      } else {
        setDistrictName((java.lang.String)value);
      }
      break;

    case PROVINCE_NAME:
      if (value == null) {
        unsetProvinceName();
      } else {
        setProvinceName((java.lang.String)value);
      }
      break;

    case OWNER_NAME:
      if (value == null) {
        unsetOwnerName();
      } else {
        setOwnerName((java.lang.String)value);
      }
      break;

    case THUMBNAIL_URL:
      if (value == null) {
        unsetThumbnailUrl();
      } else {
        setThumbnailUrl((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CAR:
      return getCar();

    case BRAND_NAME:
      return getBrandName();

    case DISTRICT_NAME:
      return getDistrictName();

    case PROVINCE_NAME:
      return getProvinceName();

    case OWNER_NAME:
      return getOwnerName();

    case THUMBNAIL_URL:
      return getThumbnailUrl();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CAR:
      return isSetCar();
    case BRAND_NAME:
      return isSetBrandName();
    case DISTRICT_NAME:
      return isSetDistrictName();
    case PROVINCE_NAME:
      return isSetProvinceName();
    case OWNER_NAME:
      return isSetOwnerName();
    case THUMBNAIL_URL:
      return isSetThumbnailUrl();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TCarView)
      return this.equals((TCarView)that);
    return false;
  }

  public boolean equals(TCarView that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_car = true && this.isSetCar();
    boolean that_present_car = true && that.isSetCar();
    if (this_present_car || that_present_car) {
      if (!(this_present_car && that_present_car))
        return false;
      if (!this.car.equals(that.car))
        return false;
    }

    boolean this_present_brandName = true && this.isSetBrandName();
    boolean that_present_brandName = true && that.isSetBrandName();
    if (this_present_brandName || that_present_brandName) {
      if (!(this_present_brandName && that_present_brandName))
        return false;
      if (!this.brandName.equals(that.brandName))
        return false;
    }

    boolean this_present_districtName = true && this.isSetDistrictName();
    boolean that_present_districtName = true && that.isSetDistrictName();
    if (this_present_districtName || that_present_districtName) {
      if (!(this_present_districtName && that_present_districtName))
        return false;
      if (!this.districtName.equals(that.districtName))
        return false;
    }

    boolean this_present_provinceName = true && this.isSetProvinceName();
    boolean that_present_provinceName = true && that.isSetProvinceName();
    if (this_present_provinceName || that_present_provinceName) {
      if (!(this_present_provinceName && that_present_provinceName))
        return false;
      if (!this.provinceName.equals(that.provinceName))
        return false;
    }

    boolean this_present_ownerName = true && this.isSetOwnerName();
    boolean that_present_ownerName = true && that.isSetOwnerName();
    if (this_present_ownerName || that_present_ownerName) {
      if (!(this_present_ownerName && that_present_ownerName))
        return false;
      if (!this.ownerName.equals(that.ownerName))
        return false;
    }

    boolean this_present_thumbnailUrl = true && this.isSetThumbnailUrl();
    boolean that_present_thumbnailUrl = true && that.isSetThumbnailUrl();
    if (this_present_thumbnailUrl || that_present_thumbnailUrl) {
      if (!(this_present_thumbnailUrl && that_present_thumbnailUrl))
        return false;
      if (!this.thumbnailUrl.equals(that.thumbnailUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCar()) ? 131071 : 524287);
    if (isSetCar())
      hashCode = hashCode * 8191 + car.hashCode();

    hashCode = hashCode * 8191 + ((isSetBrandName()) ? 131071 : 524287);
    if (isSetBrandName())
      hashCode = hashCode * 8191 + brandName.hashCode();

    hashCode = hashCode * 8191 + ((isSetDistrictName()) ? 131071 : 524287);
    if (isSetDistrictName())
      hashCode = hashCode * 8191 + districtName.hashCode();

    hashCode = hashCode * 8191 + ((isSetProvinceName()) ? 131071 : 524287);
    if (isSetProvinceName())
      hashCode = hashCode * 8191 + provinceName.hashCode();

    hashCode = hashCode * 8191 + ((isSetOwnerName()) ? 131071 : 524287);
    if (isSetOwnerName())
      hashCode = hashCode * 8191 + ownerName.hashCode();

    hashCode = hashCode * 8191 + ((isSetThumbnailUrl()) ? 131071 : 524287);
    if (isSetThumbnailUrl())
      hashCode = hashCode * 8191 + thumbnailUrl.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TCarView other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCar()).compareTo(other.isSetCar());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCar()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.car, other.car);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBrandName()).compareTo(other.isSetBrandName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrandName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brandName, other.brandName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDistrictName()).compareTo(other.isSetDistrictName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistrictName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.districtName, other.districtName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProvinceName()).compareTo(other.isSetProvinceName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvinceName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provinceName, other.provinceName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOwnerName()).compareTo(other.isSetOwnerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerName, other.ownerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetThumbnailUrl()).compareTo(other.isSetThumbnailUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetThumbnailUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.thumbnailUrl, other.thumbnailUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TCarView(");
    boolean first = true;

    sb.append("car:");
    if (this.car == null) {
      sb.append("null");
    } else {
      sb.append(this.car);
    }
    first = false;
    if (isSetBrandName()) {
      if (!first) sb.append(", ");
      sb.append("brandName:");
      if (this.brandName == null) {
        sb.append("null");
      } else {
        sb.append(this.brandName);
      }
      first = false;
    }
    if (isSetDistrictName()) {
      if (!first) sb.append(", ");
      sb.append("districtName:");
      if (this.districtName == null) {
        sb.append("null");
      } else {
        sb.append(this.districtName);
      }
      first = false;
    }
    if (isSetProvinceName()) {
      if (!first) sb.append(", ");
      sb.append("provinceName:");
      if (this.provinceName == null) {
        sb.append("null");
      } else {
        sb.append(this.provinceName);
      }
      first = false;
    }
    if (isSetOwnerName()) {
      if (!first) sb.append(", ");
      sb.append("ownerName:");
      if (this.ownerName == null) {
        sb.append("null");
      } else {
        sb.append(this.ownerName);
      }
      first = false;
    }
    if (isSetThumbnailUrl()) {
      if (!first) sb.append(", ");
      sb.append("thumbnailUrl:");
      if (this.thumbnailUrl == null) {
        sb.append("null");
      } else {
        sb.append(this.thumbnailUrl);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (car != null) {
      car.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TCarViewStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarViewStandardScheme getScheme() {
      return new TCarViewStandardScheme();
    }
  }

  private static class TCarViewStandardScheme extends org.apache.thrift.scheme.StandardScheme<TCarView> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TCarView struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.car = new TCar();
              struct.car.read(iprot);
              struct.setCarIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BRAND_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brandName = iprot.readString();
              struct.setBrandNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DISTRICT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.districtName = iprot.readString();
              struct.setDistrictNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PROVINCE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.provinceName = iprot.readString();
              struct.setProvinceNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // OWNER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ownerName = iprot.readString();
              struct.setOwnerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // THUMBNAIL_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.thumbnailUrl = iprot.readString();
              struct.setThumbnailUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TCarView struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.car != null) {
        oprot.writeFieldBegin(CAR_FIELD_DESC);
        struct.car.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.brandName != null) {
        if (struct.isSetBrandName()) {
          oprot.writeFieldBegin(BRAND_NAME_FIELD_DESC);
          oprot.writeString(struct.brandName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.districtName != null) {
        if (struct.isSetDistrictName()) {
          oprot.writeFieldBegin(DISTRICT_NAME_FIELD_DESC);
          oprot.writeString(struct.districtName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.provinceName != null) {
        if (struct.isSetProvinceName()) {
          oprot.writeFieldBegin(PROVINCE_NAME_FIELD_DESC);
          oprot.writeString(struct.provinceName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.ownerName != null) {
        if (struct.isSetOwnerName()) {
          oprot.writeFieldBegin(OWNER_NAME_FIELD_DESC);
          oprot.writeString(struct.ownerName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.thumbnailUrl != null) {
        if (struct.isSetThumbnailUrl()) {
          oprot.writeFieldBegin(THUMBNAIL_URL_FIELD_DESC);
          oprot.writeString(struct.thumbnailUrl);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TCarViewTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarViewTupleScheme getScheme() {
      return new TCarViewTupleScheme();
    }
  }

  private static class TCarViewTupleScheme extends org.apache.thrift.scheme.TupleScheme<TCarView> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TCarView struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCar()) {
        optionals.set(0);
      }
      if (struct.isSetBrandName()) {
        optionals.set(1);
      }
      if (struct.isSetDistrictName()) {
        optionals.set(2);
      }
      if (struct.isSetProvinceName()) {
        optionals.set(3);
      }
      if (struct.isSetOwnerName()) {
        optionals.set(4);
      }
      if (struct.isSetThumbnailUrl()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetCar()) {
        struct.car.write(oprot);
      }
      if (struct.isSetBrandName()) {
        oprot.writeString(struct.brandName);
      }
      if (struct.isSetDistrictName()) {
        oprot.writeString(struct.districtName);
      }
      if (struct.isSetProvinceName()) {
        oprot.writeString(struct.provinceName);
      }
      if (struct.isSetOwnerName()) {
        oprot.writeString(struct.ownerName);
      }
      if (struct.isSetThumbnailUrl()) {
        oprot.writeString(struct.thumbnailUrl);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TCarView struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.car = new TCar();
        struct.car.read(iprot);
        struct.setCarIsSet(true);
      }
      if (incoming.get(1)) {
        struct.brandName = iprot.readString();
        struct.setBrandNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.districtName = iprot.readString();
        struct.setDistrictNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.provinceName = iprot.readString();
        struct.setProvinceNameIsSet(true);
      }
      if (incoming.get(4)) {
        struct.ownerName = iprot.readString();
        struct.setOwnerNameIsSet(true);
      }
      if (incoming.get(5)) {
        struct.thumbnailUrl = iprot.readString();
        struct.setThumbnailUrlIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

