/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-28")
public class TCarBrand implements org.apache.thrift.TBase<TCarBrand, TCarBrand._Fields>, java.io.Serializable, Cloneable, Comparable<TCarBrand> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TCarBrand");

  private static final org.apache.thrift.protocol.TField CAR_BRAND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("carBrandId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_BRAND_FIELD_DESC = new org.apache.thrift.protocol.TField("nameBrand", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CREATED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("createdAt", org.apache.thrift.protocol.TType.I64, (short)20);
  private static final org.apache.thrift.protocol.TField UPDATED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("updatedAt", org.apache.thrift.protocol.TType.I64, (short)21);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TCarBrandStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TCarBrandTupleSchemeFactory();

  public int carBrandId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String nameBrand; // optional
  public long createdAt; // optional
  public long updatedAt; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAR_BRAND_ID((short)1, "carBrandId"),
    NAME_BRAND((short)2, "nameBrand"),
    CREATED_AT((short)20, "createdAt"),
    UPDATED_AT((short)21, "updatedAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAR_BRAND_ID
          return CAR_BRAND_ID;
        case 2: // NAME_BRAND
          return NAME_BRAND;
        case 20: // CREATED_AT
          return CREATED_AT;
        case 21: // UPDATED_AT
          return UPDATED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CARBRANDID_ISSET_ID = 0;
  private static final int __CREATEDAT_ISSET_ID = 1;
  private static final int __UPDATEDAT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.CAR_BRAND_ID,_Fields.NAME_BRAND,_Fields.CREATED_AT,_Fields.UPDATED_AT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAR_BRAND_ID, new org.apache.thrift.meta_data.FieldMetaData("carBrandId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NAME_BRAND, new org.apache.thrift.meta_data.FieldMetaData("nameBrand", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATED_AT, new org.apache.thrift.meta_data.FieldMetaData("createdAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UPDATED_AT, new org.apache.thrift.meta_data.FieldMetaData("updatedAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TCarBrand.class, metaDataMap);
  }

  public TCarBrand() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TCarBrand(TCarBrand other) {
    __isset_bitfield = other.__isset_bitfield;
    this.carBrandId = other.carBrandId;
    if (other.isSetNameBrand()) {
      this.nameBrand = other.nameBrand;
    }
    this.createdAt = other.createdAt;
    this.updatedAt = other.updatedAt;
  }

  public TCarBrand deepCopy() {
    return new TCarBrand(this);
  }

  @Override
  public void clear() {
    setCarBrandIdIsSet(false);
    this.carBrandId = 0;
    this.nameBrand = null;
    setCreatedAtIsSet(false);
    this.createdAt = 0;
    setUpdatedAtIsSet(false);
    this.updatedAt = 0;
  }

  public int getCarBrandId() {
    return this.carBrandId;
  }

  public TCarBrand setCarBrandId(int carBrandId) {
    this.carBrandId = carBrandId;
    setCarBrandIdIsSet(true);
    return this;
  }

  public void unsetCarBrandId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CARBRANDID_ISSET_ID);
  }

  /** Returns true if field carBrandId is set (has been assigned a value) and false otherwise */
  public boolean isSetCarBrandId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CARBRANDID_ISSET_ID);
  }

  public void setCarBrandIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CARBRANDID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNameBrand() {
    return this.nameBrand;
  }

  public TCarBrand setNameBrand(@org.apache.thrift.annotation.Nullable java.lang.String nameBrand) {
    this.nameBrand = nameBrand;
    return this;
  }

  public void unsetNameBrand() {
    this.nameBrand = null;
  }

  /** Returns true if field nameBrand is set (has been assigned a value) and false otherwise */
  public boolean isSetNameBrand() {
    return this.nameBrand != null;
  }

  public void setNameBrandIsSet(boolean value) {
    if (!value) {
      this.nameBrand = null;
    }
  }

  public long getCreatedAt() {
    return this.createdAt;
  }

  public TCarBrand setCreatedAt(long createdAt) {
    this.createdAt = createdAt;
    setCreatedAtIsSet(true);
    return this;
  }

  public void unsetCreatedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  /** Returns true if field createdAt is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  public void setCreatedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEDAT_ISSET_ID, value);
  }

  public long getUpdatedAt() {
    return this.updatedAt;
  }

  public TCarBrand setUpdatedAt(long updatedAt) {
    this.updatedAt = updatedAt;
    setUpdatedAtIsSet(true);
    return this;
  }

  public void unsetUpdatedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UPDATEDAT_ISSET_ID);
  }

  /** Returns true if field updatedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdatedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UPDATEDAT_ISSET_ID);
  }

  public void setUpdatedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UPDATEDAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CAR_BRAND_ID:
      if (value == null) {
        unsetCarBrandId();
      } else {
        setCarBrandId((java.lang.Integer)value);
      }
      break;

    case NAME_BRAND:
      if (value == null) {
        unsetNameBrand();
      } else {
        setNameBrand((java.lang.String)value);
      }
      break;

    case CREATED_AT:
      if (value == null) {
        unsetCreatedAt();
      } else {
        setCreatedAt((java.lang.Long)value);
      }
      break;

    case UPDATED_AT:
      if (value == null) {
        unsetUpdatedAt();
      } else {
        setUpdatedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CAR_BRAND_ID:
      return getCarBrandId();

    case NAME_BRAND:
      return getNameBrand();

    case CREATED_AT:
      return getCreatedAt();

    case UPDATED_AT:
      return getUpdatedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CAR_BRAND_ID:
      return isSetCarBrandId();
    case NAME_BRAND:
      return isSetNameBrand();
    case CREATED_AT:
      return isSetCreatedAt();
    case UPDATED_AT:
      return isSetUpdatedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TCarBrand)
      return this.equals((TCarBrand)that);
    return false;
  }

  public boolean equals(TCarBrand that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_carBrandId = true && this.isSetCarBrandId();
    boolean that_present_carBrandId = true && that.isSetCarBrandId();
    if (this_present_carBrandId || that_present_carBrandId) {
      if (!(this_present_carBrandId && that_present_carBrandId))
        return false;
      if (this.carBrandId != that.carBrandId)
        return false;
    }

    boolean this_present_nameBrand = true && this.isSetNameBrand();
    boolean that_present_nameBrand = true && that.isSetNameBrand();
    if (this_present_nameBrand || that_present_nameBrand) {
      if (!(this_present_nameBrand && that_present_nameBrand))
        return false;
      if (!this.nameBrand.equals(that.nameBrand))
        return false;
    }

    boolean this_present_createdAt = true && this.isSetCreatedAt();
    boolean that_present_createdAt = true && that.isSetCreatedAt();
    if (this_present_createdAt || that_present_createdAt) {
      if (!(this_present_createdAt && that_present_createdAt))
        return false;
      if (this.createdAt != that.createdAt)
        return false;
    }

    boolean this_present_updatedAt = true && this.isSetUpdatedAt();
    boolean that_present_updatedAt = true && that.isSetUpdatedAt();
    if (this_present_updatedAt || that_present_updatedAt) {
      if (!(this_present_updatedAt && that_present_updatedAt))
        return false;
      if (this.updatedAt != that.updatedAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCarBrandId()) ? 131071 : 524287);
    if (isSetCarBrandId())
      hashCode = hashCode * 8191 + carBrandId;

    hashCode = hashCode * 8191 + ((isSetNameBrand()) ? 131071 : 524287);
    if (isSetNameBrand())
      hashCode = hashCode * 8191 + nameBrand.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreatedAt()) ? 131071 : 524287);
    if (isSetCreatedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createdAt);

    hashCode = hashCode * 8191 + ((isSetUpdatedAt()) ? 131071 : 524287);
    if (isSetUpdatedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(updatedAt);

    return hashCode;
  }

  @Override
  public int compareTo(TCarBrand other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCarBrandId()).compareTo(other.isSetCarBrandId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarBrandId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.carBrandId, other.carBrandId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNameBrand()).compareTo(other.isSetNameBrand());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNameBrand()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nameBrand, other.nameBrand);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreatedAt()).compareTo(other.isSetCreatedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdAt, other.createdAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetUpdatedAt()).compareTo(other.isSetUpdatedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdatedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updatedAt, other.updatedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TCarBrand(");
    boolean first = true;

    if (isSetCarBrandId()) {
      sb.append("carBrandId:");
      sb.append(this.carBrandId);
      first = false;
    }
    if (isSetNameBrand()) {
      if (!first) sb.append(", ");
      sb.append("nameBrand:");
      if (this.nameBrand == null) {
        sb.append("null");
      } else {
        sb.append(this.nameBrand);
      }
      first = false;
    }
    if (isSetCreatedAt()) {
      if (!first) sb.append(", ");
      sb.append("createdAt:");
      sb.append(this.createdAt);
      first = false;
    }
    if (isSetUpdatedAt()) {
      if (!first) sb.append(", ");
      sb.append("updatedAt:");
      sb.append(this.updatedAt);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TCarBrandStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarBrandStandardScheme getScheme() {
      return new TCarBrandStandardScheme();
    }
  }

  private static class TCarBrandStandardScheme extends org.apache.thrift.scheme.StandardScheme<TCarBrand> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TCarBrand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAR_BRAND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.carBrandId = iprot.readI32();
              struct.setCarBrandIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME_BRAND
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nameBrand = iprot.readString();
              struct.setNameBrandIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // CREATED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createdAt = iprot.readI64();
              struct.setCreatedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 21: // UPDATED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.updatedAt = iprot.readI64();
              struct.setUpdatedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TCarBrand struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetCarBrandId()) {
        oprot.writeFieldBegin(CAR_BRAND_ID_FIELD_DESC);
        oprot.writeI32(struct.carBrandId);
        oprot.writeFieldEnd();
      }
      if (struct.nameBrand != null) {
        if (struct.isSetNameBrand()) {
          oprot.writeFieldBegin(NAME_BRAND_FIELD_DESC);
          oprot.writeString(struct.nameBrand);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeFieldBegin(CREATED_AT_FIELD_DESC);
        oprot.writeI64(struct.createdAt);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUpdatedAt()) {
        oprot.writeFieldBegin(UPDATED_AT_FIELD_DESC);
        oprot.writeI64(struct.updatedAt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TCarBrandTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarBrandTupleScheme getScheme() {
      return new TCarBrandTupleScheme();
    }
  }

  private static class TCarBrandTupleScheme extends org.apache.thrift.scheme.TupleScheme<TCarBrand> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TCarBrand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCarBrandId()) {
        optionals.set(0);
      }
      if (struct.isSetNameBrand()) {
        optionals.set(1);
      }
      if (struct.isSetCreatedAt()) {
        optionals.set(2);
      }
      if (struct.isSetUpdatedAt()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetCarBrandId()) {
        oprot.writeI32(struct.carBrandId);
      }
      if (struct.isSetNameBrand()) {
        oprot.writeString(struct.nameBrand);
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeI64(struct.createdAt);
      }
      if (struct.isSetUpdatedAt()) {
        oprot.writeI64(struct.updatedAt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TCarBrand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.carBrandId = iprot.readI32();
        struct.setCarBrandIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nameBrand = iprot.readString();
        struct.setNameBrandIsSet(true);
      }
      if (incoming.get(2)) {
        struct.createdAt = iprot.readI64();
        struct.setCreatedAtIsSet(true);
      }
      if (incoming.get(3)) {
        struct.updatedAt = iprot.readI64();
        struct.setUpdatedAtIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

