/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-10-08")
public class TCarFilterRequest implements org.apache.thrift.TBase<TCarFilterRequest, TCarFilterRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TCarFilterRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TCarFilterRequest");

  private static final org.apache.thrift.protocol.TField CAR_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("carName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRODUCTION_YEAR_FIELD_DESC = new org.apache.thrift.protocol.TField("productionYear", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField CAR_BRAND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("carBrandId", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField NUM_SEATS_FIELD_DESC = new org.apache.thrift.protocol.TField("numSeats", org.apache.thrift.protocol.TType.BYTE, (short)4);
  private static final org.apache.thrift.protocol.TField TRANSMISSION_FIELD_DESC = new org.apache.thrift.protocol.TField("transmission", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField TYPE_FUEL_FIELD_DESC = new org.apache.thrift.protocol.TField("typeFuel", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField FUEL_CONSUMPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("fuelConsumption", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField PRICE_PER_DAY_FIELD_DESC = new org.apache.thrift.protocol.TField("pricePerDay", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField DISTRICT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("districtId", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField PROVINCE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("provinceId", org.apache.thrift.protocol.TType.I32, (short)12);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TCarFilterRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TCarFilterRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String carName; // optional
  public int productionYear; // optional
  public int carBrandId; // optional
  public byte numSeats; // optional
  /**
   * 
   * @see TTransmission
   */
  public @org.apache.thrift.annotation.Nullable TTransmission transmission; // optional
  /**
   * 
   * @see TTypeFuel
   */
  public @org.apache.thrift.annotation.Nullable TTypeFuel typeFuel; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String fuelConsumption; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String pricePerDay; // optional
  public int districtId; // optional
  public int provinceId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAR_NAME((short)1, "carName"),
    PRODUCTION_YEAR((short)2, "productionYear"),
    CAR_BRAND_ID((short)3, "carBrandId"),
    NUM_SEATS((short)4, "numSeats"),
    /**
     * 
     * @see TTransmission
     */
    TRANSMISSION((short)5, "transmission"),
    /**
     * 
     * @see TTypeFuel
     */
    TYPE_FUEL((short)6, "typeFuel"),
    FUEL_CONSUMPTION((short)7, "fuelConsumption"),
    PRICE_PER_DAY((short)9, "pricePerDay"),
    DISTRICT_ID((short)11, "districtId"),
    PROVINCE_ID((short)12, "provinceId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAR_NAME
          return CAR_NAME;
        case 2: // PRODUCTION_YEAR
          return PRODUCTION_YEAR;
        case 3: // CAR_BRAND_ID
          return CAR_BRAND_ID;
        case 4: // NUM_SEATS
          return NUM_SEATS;
        case 5: // TRANSMISSION
          return TRANSMISSION;
        case 6: // TYPE_FUEL
          return TYPE_FUEL;
        case 7: // FUEL_CONSUMPTION
          return FUEL_CONSUMPTION;
        case 9: // PRICE_PER_DAY
          return PRICE_PER_DAY;
        case 11: // DISTRICT_ID
          return DISTRICT_ID;
        case 12: // PROVINCE_ID
          return PROVINCE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRODUCTIONYEAR_ISSET_ID = 0;
  private static final int __CARBRANDID_ISSET_ID = 1;
  private static final int __NUMSEATS_ISSET_ID = 2;
  private static final int __DISTRICTID_ISSET_ID = 3;
  private static final int __PROVINCEID_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.CAR_NAME,_Fields.PRODUCTION_YEAR,_Fields.CAR_BRAND_ID,_Fields.NUM_SEATS,_Fields.TRANSMISSION,_Fields.TYPE_FUEL,_Fields.FUEL_CONSUMPTION,_Fields.PRICE_PER_DAY,_Fields.DISTRICT_ID,_Fields.PROVINCE_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAR_NAME, new org.apache.thrift.meta_data.FieldMetaData("carName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRODUCTION_YEAR, new org.apache.thrift.meta_data.FieldMetaData("productionYear", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CAR_BRAND_ID, new org.apache.thrift.meta_data.FieldMetaData("carBrandId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NUM_SEATS, new org.apache.thrift.meta_data.FieldMetaData("numSeats", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.TRANSMISSION, new org.apache.thrift.meta_data.FieldMetaData("transmission", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TTransmission.class)));
    tmpMap.put(_Fields.TYPE_FUEL, new org.apache.thrift.meta_data.FieldMetaData("typeFuel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TTypeFuel.class)));
    tmpMap.put(_Fields.FUEL_CONSUMPTION, new org.apache.thrift.meta_data.FieldMetaData("fuelConsumption", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRICE_PER_DAY, new org.apache.thrift.meta_data.FieldMetaData("pricePerDay", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISTRICT_ID, new org.apache.thrift.meta_data.FieldMetaData("districtId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PROVINCE_ID, new org.apache.thrift.meta_data.FieldMetaData("provinceId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TCarFilterRequest.class, metaDataMap);
  }

  public TCarFilterRequest() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TCarFilterRequest(TCarFilterRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCarName()) {
      this.carName = other.carName;
    }
    this.productionYear = other.productionYear;
    this.carBrandId = other.carBrandId;
    this.numSeats = other.numSeats;
    if (other.isSetTransmission()) {
      this.transmission = other.transmission;
    }
    if (other.isSetTypeFuel()) {
      this.typeFuel = other.typeFuel;
    }
    if (other.isSetFuelConsumption()) {
      this.fuelConsumption = other.fuelConsumption;
    }
    if (other.isSetPricePerDay()) {
      this.pricePerDay = other.pricePerDay;
    }
    this.districtId = other.districtId;
    this.provinceId = other.provinceId;
  }

  public TCarFilterRequest deepCopy() {
    return new TCarFilterRequest(this);
  }

  @Override
  public void clear() {
    this.carName = null;
    setProductionYearIsSet(false);
    this.productionYear = 0;
    setCarBrandIdIsSet(false);
    this.carBrandId = 0;
    setNumSeatsIsSet(false);
    this.numSeats = 0;
    this.transmission = null;
    this.typeFuel = null;
    this.fuelConsumption = null;
    this.pricePerDay = null;
    setDistrictIdIsSet(false);
    this.districtId = 0;
    setProvinceIdIsSet(false);
    this.provinceId = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCarName() {
    return this.carName;
  }

  public TCarFilterRequest setCarName(@org.apache.thrift.annotation.Nullable java.lang.String carName) {
    this.carName = carName;
    return this;
  }

  public void unsetCarName() {
    this.carName = null;
  }

  /** Returns true if field carName is set (has been assigned a value) and false otherwise */
  public boolean isSetCarName() {
    return this.carName != null;
  }

  public void setCarNameIsSet(boolean value) {
    if (!value) {
      this.carName = null;
    }
  }

  public int getProductionYear() {
    return this.productionYear;
  }

  public TCarFilterRequest setProductionYear(int productionYear) {
    this.productionYear = productionYear;
    setProductionYearIsSet(true);
    return this;
  }

  public void unsetProductionYear() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRODUCTIONYEAR_ISSET_ID);
  }

  /** Returns true if field productionYear is set (has been assigned a value) and false otherwise */
  public boolean isSetProductionYear() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRODUCTIONYEAR_ISSET_ID);
  }

  public void setProductionYearIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRODUCTIONYEAR_ISSET_ID, value);
  }

  public int getCarBrandId() {
    return this.carBrandId;
  }

  public TCarFilterRequest setCarBrandId(int carBrandId) {
    this.carBrandId = carBrandId;
    setCarBrandIdIsSet(true);
    return this;
  }

  public void unsetCarBrandId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CARBRANDID_ISSET_ID);
  }

  /** Returns true if field carBrandId is set (has been assigned a value) and false otherwise */
  public boolean isSetCarBrandId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CARBRANDID_ISSET_ID);
  }

  public void setCarBrandIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CARBRANDID_ISSET_ID, value);
  }

  public byte getNumSeats() {
    return this.numSeats;
  }

  public TCarFilterRequest setNumSeats(byte numSeats) {
    this.numSeats = numSeats;
    setNumSeatsIsSet(true);
    return this;
  }

  public void unsetNumSeats() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMSEATS_ISSET_ID);
  }

  /** Returns true if field numSeats is set (has been assigned a value) and false otherwise */
  public boolean isSetNumSeats() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMSEATS_ISSET_ID);
  }

  public void setNumSeatsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMSEATS_ISSET_ID, value);
  }

  /**
   * 
   * @see TTransmission
   */
  @org.apache.thrift.annotation.Nullable
  public TTransmission getTransmission() {
    return this.transmission;
  }

  /**
   * 
   * @see TTransmission
   */
  public TCarFilterRequest setTransmission(@org.apache.thrift.annotation.Nullable TTransmission transmission) {
    this.transmission = transmission;
    return this;
  }

  public void unsetTransmission() {
    this.transmission = null;
  }

  /** Returns true if field transmission is set (has been assigned a value) and false otherwise */
  public boolean isSetTransmission() {
    return this.transmission != null;
  }

  public void setTransmissionIsSet(boolean value) {
    if (!value) {
      this.transmission = null;
    }
  }

  /**
   * 
   * @see TTypeFuel
   */
  @org.apache.thrift.annotation.Nullable
  public TTypeFuel getTypeFuel() {
    return this.typeFuel;
  }

  /**
   * 
   * @see TTypeFuel
   */
  public TCarFilterRequest setTypeFuel(@org.apache.thrift.annotation.Nullable TTypeFuel typeFuel) {
    this.typeFuel = typeFuel;
    return this;
  }

  public void unsetTypeFuel() {
    this.typeFuel = null;
  }

  /** Returns true if field typeFuel is set (has been assigned a value) and false otherwise */
  public boolean isSetTypeFuel() {
    return this.typeFuel != null;
  }

  public void setTypeFuelIsSet(boolean value) {
    if (!value) {
      this.typeFuel = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getFuelConsumption() {
    return this.fuelConsumption;
  }

  public TCarFilterRequest setFuelConsumption(@org.apache.thrift.annotation.Nullable java.lang.String fuelConsumption) {
    this.fuelConsumption = fuelConsumption;
    return this;
  }

  public void unsetFuelConsumption() {
    this.fuelConsumption = null;
  }

  /** Returns true if field fuelConsumption is set (has been assigned a value) and false otherwise */
  public boolean isSetFuelConsumption() {
    return this.fuelConsumption != null;
  }

  public void setFuelConsumptionIsSet(boolean value) {
    if (!value) {
      this.fuelConsumption = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPricePerDay() {
    return this.pricePerDay;
  }

  public TCarFilterRequest setPricePerDay(@org.apache.thrift.annotation.Nullable java.lang.String pricePerDay) {
    this.pricePerDay = pricePerDay;
    return this;
  }

  public void unsetPricePerDay() {
    this.pricePerDay = null;
  }

  /** Returns true if field pricePerDay is set (has been assigned a value) and false otherwise */
  public boolean isSetPricePerDay() {
    return this.pricePerDay != null;
  }

  public void setPricePerDayIsSet(boolean value) {
    if (!value) {
      this.pricePerDay = null;
    }
  }

  public int getDistrictId() {
    return this.districtId;
  }

  public TCarFilterRequest setDistrictId(int districtId) {
    this.districtId = districtId;
    setDistrictIdIsSet(true);
    return this;
  }

  public void unsetDistrictId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISTRICTID_ISSET_ID);
  }

  /** Returns true if field districtId is set (has been assigned a value) and false otherwise */
  public boolean isSetDistrictId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISTRICTID_ISSET_ID);
  }

  public void setDistrictIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISTRICTID_ISSET_ID, value);
  }

  public int getProvinceId() {
    return this.provinceId;
  }

  public TCarFilterRequest setProvinceId(int provinceId) {
    this.provinceId = provinceId;
    setProvinceIdIsSet(true);
    return this;
  }

  public void unsetProvinceId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PROVINCEID_ISSET_ID);
  }

  /** Returns true if field provinceId is set (has been assigned a value) and false otherwise */
  public boolean isSetProvinceId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PROVINCEID_ISSET_ID);
  }

  public void setProvinceIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PROVINCEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CAR_NAME:
      if (value == null) {
        unsetCarName();
      } else {
        setCarName((java.lang.String)value);
      }
      break;

    case PRODUCTION_YEAR:
      if (value == null) {
        unsetProductionYear();
      } else {
        setProductionYear((java.lang.Integer)value);
      }
      break;

    case CAR_BRAND_ID:
      if (value == null) {
        unsetCarBrandId();
      } else {
        setCarBrandId((java.lang.Integer)value);
      }
      break;

    case NUM_SEATS:
      if (value == null) {
        unsetNumSeats();
      } else {
        setNumSeats((java.lang.Byte)value);
      }
      break;

    case TRANSMISSION:
      if (value == null) {
        unsetTransmission();
      } else {
        setTransmission((TTransmission)value);
      }
      break;

    case TYPE_FUEL:
      if (value == null) {
        unsetTypeFuel();
      } else {
        setTypeFuel((TTypeFuel)value);
      }
      break;

    case FUEL_CONSUMPTION:
      if (value == null) {
        unsetFuelConsumption();
      } else {
        setFuelConsumption((java.lang.String)value);
      }
      break;

    case PRICE_PER_DAY:
      if (value == null) {
        unsetPricePerDay();
      } else {
        setPricePerDay((java.lang.String)value);
      }
      break;

    case DISTRICT_ID:
      if (value == null) {
        unsetDistrictId();
      } else {
        setDistrictId((java.lang.Integer)value);
      }
      break;

    case PROVINCE_ID:
      if (value == null) {
        unsetProvinceId();
      } else {
        setProvinceId((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CAR_NAME:
      return getCarName();

    case PRODUCTION_YEAR:
      return getProductionYear();

    case CAR_BRAND_ID:
      return getCarBrandId();

    case NUM_SEATS:
      return getNumSeats();

    case TRANSMISSION:
      return getTransmission();

    case TYPE_FUEL:
      return getTypeFuel();

    case FUEL_CONSUMPTION:
      return getFuelConsumption();

    case PRICE_PER_DAY:
      return getPricePerDay();

    case DISTRICT_ID:
      return getDistrictId();

    case PROVINCE_ID:
      return getProvinceId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CAR_NAME:
      return isSetCarName();
    case PRODUCTION_YEAR:
      return isSetProductionYear();
    case CAR_BRAND_ID:
      return isSetCarBrandId();
    case NUM_SEATS:
      return isSetNumSeats();
    case TRANSMISSION:
      return isSetTransmission();
    case TYPE_FUEL:
      return isSetTypeFuel();
    case FUEL_CONSUMPTION:
      return isSetFuelConsumption();
    case PRICE_PER_DAY:
      return isSetPricePerDay();
    case DISTRICT_ID:
      return isSetDistrictId();
    case PROVINCE_ID:
      return isSetProvinceId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TCarFilterRequest)
      return this.equals((TCarFilterRequest)that);
    return false;
  }

  public boolean equals(TCarFilterRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_carName = true && this.isSetCarName();
    boolean that_present_carName = true && that.isSetCarName();
    if (this_present_carName || that_present_carName) {
      if (!(this_present_carName && that_present_carName))
        return false;
      if (!this.carName.equals(that.carName))
        return false;
    }

    boolean this_present_productionYear = true && this.isSetProductionYear();
    boolean that_present_productionYear = true && that.isSetProductionYear();
    if (this_present_productionYear || that_present_productionYear) {
      if (!(this_present_productionYear && that_present_productionYear))
        return false;
      if (this.productionYear != that.productionYear)
        return false;
    }

    boolean this_present_carBrandId = true && this.isSetCarBrandId();
    boolean that_present_carBrandId = true && that.isSetCarBrandId();
    if (this_present_carBrandId || that_present_carBrandId) {
      if (!(this_present_carBrandId && that_present_carBrandId))
        return false;
      if (this.carBrandId != that.carBrandId)
        return false;
    }

    boolean this_present_numSeats = true && this.isSetNumSeats();
    boolean that_present_numSeats = true && that.isSetNumSeats();
    if (this_present_numSeats || that_present_numSeats) {
      if (!(this_present_numSeats && that_present_numSeats))
        return false;
      if (this.numSeats != that.numSeats)
        return false;
    }

    boolean this_present_transmission = true && this.isSetTransmission();
    boolean that_present_transmission = true && that.isSetTransmission();
    if (this_present_transmission || that_present_transmission) {
      if (!(this_present_transmission && that_present_transmission))
        return false;
      if (!this.transmission.equals(that.transmission))
        return false;
    }

    boolean this_present_typeFuel = true && this.isSetTypeFuel();
    boolean that_present_typeFuel = true && that.isSetTypeFuel();
    if (this_present_typeFuel || that_present_typeFuel) {
      if (!(this_present_typeFuel && that_present_typeFuel))
        return false;
      if (!this.typeFuel.equals(that.typeFuel))
        return false;
    }

    boolean this_present_fuelConsumption = true && this.isSetFuelConsumption();
    boolean that_present_fuelConsumption = true && that.isSetFuelConsumption();
    if (this_present_fuelConsumption || that_present_fuelConsumption) {
      if (!(this_present_fuelConsumption && that_present_fuelConsumption))
        return false;
      if (!this.fuelConsumption.equals(that.fuelConsumption))
        return false;
    }

    boolean this_present_pricePerDay = true && this.isSetPricePerDay();
    boolean that_present_pricePerDay = true && that.isSetPricePerDay();
    if (this_present_pricePerDay || that_present_pricePerDay) {
      if (!(this_present_pricePerDay && that_present_pricePerDay))
        return false;
      if (!this.pricePerDay.equals(that.pricePerDay))
        return false;
    }

    boolean this_present_districtId = true && this.isSetDistrictId();
    boolean that_present_districtId = true && that.isSetDistrictId();
    if (this_present_districtId || that_present_districtId) {
      if (!(this_present_districtId && that_present_districtId))
        return false;
      if (this.districtId != that.districtId)
        return false;
    }

    boolean this_present_provinceId = true && this.isSetProvinceId();
    boolean that_present_provinceId = true && that.isSetProvinceId();
    if (this_present_provinceId || that_present_provinceId) {
      if (!(this_present_provinceId && that_present_provinceId))
        return false;
      if (this.provinceId != that.provinceId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCarName()) ? 131071 : 524287);
    if (isSetCarName())
      hashCode = hashCode * 8191 + carName.hashCode();

    hashCode = hashCode * 8191 + ((isSetProductionYear()) ? 131071 : 524287);
    if (isSetProductionYear())
      hashCode = hashCode * 8191 + productionYear;

    hashCode = hashCode * 8191 + ((isSetCarBrandId()) ? 131071 : 524287);
    if (isSetCarBrandId())
      hashCode = hashCode * 8191 + carBrandId;

    hashCode = hashCode * 8191 + ((isSetNumSeats()) ? 131071 : 524287);
    if (isSetNumSeats())
      hashCode = hashCode * 8191 + (int) (numSeats);

    hashCode = hashCode * 8191 + ((isSetTransmission()) ? 131071 : 524287);
    if (isSetTransmission())
      hashCode = hashCode * 8191 + transmission.getValue();

    hashCode = hashCode * 8191 + ((isSetTypeFuel()) ? 131071 : 524287);
    if (isSetTypeFuel())
      hashCode = hashCode * 8191 + typeFuel.getValue();

    hashCode = hashCode * 8191 + ((isSetFuelConsumption()) ? 131071 : 524287);
    if (isSetFuelConsumption())
      hashCode = hashCode * 8191 + fuelConsumption.hashCode();

    hashCode = hashCode * 8191 + ((isSetPricePerDay()) ? 131071 : 524287);
    if (isSetPricePerDay())
      hashCode = hashCode * 8191 + pricePerDay.hashCode();

    hashCode = hashCode * 8191 + ((isSetDistrictId()) ? 131071 : 524287);
    if (isSetDistrictId())
      hashCode = hashCode * 8191 + districtId;

    hashCode = hashCode * 8191 + ((isSetProvinceId()) ? 131071 : 524287);
    if (isSetProvinceId())
      hashCode = hashCode * 8191 + provinceId;

    return hashCode;
  }

  @Override
  public int compareTo(TCarFilterRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCarName()).compareTo(other.isSetCarName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.carName, other.carName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProductionYear()).compareTo(other.isSetProductionYear());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductionYear()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.productionYear, other.productionYear);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCarBrandId()).compareTo(other.isSetCarBrandId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarBrandId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.carBrandId, other.carBrandId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNumSeats()).compareTo(other.isSetNumSeats());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumSeats()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numSeats, other.numSeats);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTransmission()).compareTo(other.isSetTransmission());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransmission()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transmission, other.transmission);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTypeFuel()).compareTo(other.isSetTypeFuel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTypeFuel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typeFuel, other.typeFuel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFuelConsumption()).compareTo(other.isSetFuelConsumption());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFuelConsumption()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fuelConsumption, other.fuelConsumption);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPricePerDay()).compareTo(other.isSetPricePerDay());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPricePerDay()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pricePerDay, other.pricePerDay);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDistrictId()).compareTo(other.isSetDistrictId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistrictId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.districtId, other.districtId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProvinceId()).compareTo(other.isSetProvinceId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvinceId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provinceId, other.provinceId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TCarFilterRequest(");
    boolean first = true;

    if (isSetCarName()) {
      sb.append("carName:");
      if (this.carName == null) {
        sb.append("null");
      } else {
        sb.append(this.carName);
      }
      first = false;
    }
    if (isSetProductionYear()) {
      if (!first) sb.append(", ");
      sb.append("productionYear:");
      sb.append(this.productionYear);
      first = false;
    }
    if (isSetCarBrandId()) {
      if (!first) sb.append(", ");
      sb.append("carBrandId:");
      sb.append(this.carBrandId);
      first = false;
    }
    if (isSetNumSeats()) {
      if (!first) sb.append(", ");
      sb.append("numSeats:");
      sb.append(this.numSeats);
      first = false;
    }
    if (isSetTransmission()) {
      if (!first) sb.append(", ");
      sb.append("transmission:");
      if (this.transmission == null) {
        sb.append("null");
      } else {
        sb.append(this.transmission);
      }
      first = false;
    }
    if (isSetTypeFuel()) {
      if (!first) sb.append(", ");
      sb.append("typeFuel:");
      if (this.typeFuel == null) {
        sb.append("null");
      } else {
        sb.append(this.typeFuel);
      }
      first = false;
    }
    if (isSetFuelConsumption()) {
      if (!first) sb.append(", ");
      sb.append("fuelConsumption:");
      if (this.fuelConsumption == null) {
        sb.append("null");
      } else {
        sb.append(this.fuelConsumption);
      }
      first = false;
    }
    if (isSetPricePerDay()) {
      if (!first) sb.append(", ");
      sb.append("pricePerDay:");
      if (this.pricePerDay == null) {
        sb.append("null");
      } else {
        sb.append(this.pricePerDay);
      }
      first = false;
    }
    if (isSetDistrictId()) {
      if (!first) sb.append(", ");
      sb.append("districtId:");
      sb.append(this.districtId);
      first = false;
    }
    if (isSetProvinceId()) {
      if (!first) sb.append(", ");
      sb.append("provinceId:");
      sb.append(this.provinceId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TCarFilterRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarFilterRequestStandardScheme getScheme() {
      return new TCarFilterRequestStandardScheme();
    }
  }

  private static class TCarFilterRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TCarFilterRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TCarFilterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAR_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.carName = iprot.readString();
              struct.setCarNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRODUCTION_YEAR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.productionYear = iprot.readI32();
              struct.setProductionYearIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CAR_BRAND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.carBrandId = iprot.readI32();
              struct.setCarBrandIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NUM_SEATS
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.numSeats = iprot.readByte();
              struct.setNumSeatsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TRANSMISSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.transmission = thrift.TTransmission.findByValue(iprot.readI32());
              struct.setTransmissionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TYPE_FUEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.typeFuel = thrift.TTypeFuel.findByValue(iprot.readI32());
              struct.setTypeFuelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // FUEL_CONSUMPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fuelConsumption = iprot.readString();
              struct.setFuelConsumptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PRICE_PER_DAY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pricePerDay = iprot.readString();
              struct.setPricePerDayIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // DISTRICT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.districtId = iprot.readI32();
              struct.setDistrictIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // PROVINCE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.provinceId = iprot.readI32();
              struct.setProvinceIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TCarFilterRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.carName != null) {
        if (struct.isSetCarName()) {
          oprot.writeFieldBegin(CAR_NAME_FIELD_DESC);
          oprot.writeString(struct.carName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetProductionYear()) {
        oprot.writeFieldBegin(PRODUCTION_YEAR_FIELD_DESC);
        oprot.writeI32(struct.productionYear);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCarBrandId()) {
        oprot.writeFieldBegin(CAR_BRAND_ID_FIELD_DESC);
        oprot.writeI32(struct.carBrandId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetNumSeats()) {
        oprot.writeFieldBegin(NUM_SEATS_FIELD_DESC);
        oprot.writeByte(struct.numSeats);
        oprot.writeFieldEnd();
      }
      if (struct.transmission != null) {
        if (struct.isSetTransmission()) {
          oprot.writeFieldBegin(TRANSMISSION_FIELD_DESC);
          oprot.writeI32(struct.transmission.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.typeFuel != null) {
        if (struct.isSetTypeFuel()) {
          oprot.writeFieldBegin(TYPE_FUEL_FIELD_DESC);
          oprot.writeI32(struct.typeFuel.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.fuelConsumption != null) {
        if (struct.isSetFuelConsumption()) {
          oprot.writeFieldBegin(FUEL_CONSUMPTION_FIELD_DESC);
          oprot.writeString(struct.fuelConsumption);
          oprot.writeFieldEnd();
        }
      }
      if (struct.pricePerDay != null) {
        if (struct.isSetPricePerDay()) {
          oprot.writeFieldBegin(PRICE_PER_DAY_FIELD_DESC);
          oprot.writeString(struct.pricePerDay);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetDistrictId()) {
        oprot.writeFieldBegin(DISTRICT_ID_FIELD_DESC);
        oprot.writeI32(struct.districtId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetProvinceId()) {
        oprot.writeFieldBegin(PROVINCE_ID_FIELD_DESC);
        oprot.writeI32(struct.provinceId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TCarFilterRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TCarFilterRequestTupleScheme getScheme() {
      return new TCarFilterRequestTupleScheme();
    }
  }

  private static class TCarFilterRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TCarFilterRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TCarFilterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCarName()) {
        optionals.set(0);
      }
      if (struct.isSetProductionYear()) {
        optionals.set(1);
      }
      if (struct.isSetCarBrandId()) {
        optionals.set(2);
      }
      if (struct.isSetNumSeats()) {
        optionals.set(3);
      }
      if (struct.isSetTransmission()) {
        optionals.set(4);
      }
      if (struct.isSetTypeFuel()) {
        optionals.set(5);
      }
      if (struct.isSetFuelConsumption()) {
        optionals.set(6);
      }
      if (struct.isSetPricePerDay()) {
        optionals.set(7);
      }
      if (struct.isSetDistrictId()) {
        optionals.set(8);
      }
      if (struct.isSetProvinceId()) {
        optionals.set(9);
      }
      oprot.writeBitSet(optionals, 10);
      if (struct.isSetCarName()) {
        oprot.writeString(struct.carName);
      }
      if (struct.isSetProductionYear()) {
        oprot.writeI32(struct.productionYear);
      }
      if (struct.isSetCarBrandId()) {
        oprot.writeI32(struct.carBrandId);
      }
      if (struct.isSetNumSeats()) {
        oprot.writeByte(struct.numSeats);
      }
      if (struct.isSetTransmission()) {
        oprot.writeI32(struct.transmission.getValue());
      }
      if (struct.isSetTypeFuel()) {
        oprot.writeI32(struct.typeFuel.getValue());
      }
      if (struct.isSetFuelConsumption()) {
        oprot.writeString(struct.fuelConsumption);
      }
      if (struct.isSetPricePerDay()) {
        oprot.writeString(struct.pricePerDay);
      }
      if (struct.isSetDistrictId()) {
        oprot.writeI32(struct.districtId);
      }
      if (struct.isSetProvinceId()) {
        oprot.writeI32(struct.provinceId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TCarFilterRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(10);
      if (incoming.get(0)) {
        struct.carName = iprot.readString();
        struct.setCarNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.productionYear = iprot.readI32();
        struct.setProductionYearIsSet(true);
      }
      if (incoming.get(2)) {
        struct.carBrandId = iprot.readI32();
        struct.setCarBrandIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.numSeats = iprot.readByte();
        struct.setNumSeatsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.transmission = thrift.TTransmission.findByValue(iprot.readI32());
        struct.setTransmissionIsSet(true);
      }
      if (incoming.get(5)) {
        struct.typeFuel = thrift.TTypeFuel.findByValue(iprot.readI32());
        struct.setTypeFuelIsSet(true);
      }
      if (incoming.get(6)) {
        struct.fuelConsumption = iprot.readString();
        struct.setFuelConsumptionIsSet(true);
      }
      if (incoming.get(7)) {
        struct.pricePerDay = iprot.readString();
        struct.setPricePerDayIsSet(true);
      }
      if (incoming.get(8)) {
        struct.districtId = iprot.readI32();
        struct.setDistrictIdIsSet(true);
      }
      if (incoming.get(9)) {
        struct.provinceId = iprot.readI32();
        struct.setProvinceIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

