/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-28")
public class TDistrict implements org.apache.thrift.TBase<TDistrict, TDistrict._Fields>, java.io.Serializable, Cloneable, Comparable<TDistrict> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDistrict");

  private static final org.apache.thrift.protocol.TField DISTRICT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("districtId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DISTRICT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("districtName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROVINCE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("provinceId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TDistrictStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TDistrictTupleSchemeFactory();

  public int districtId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String districtName; // optional
  public int provinceId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DISTRICT_ID((short)1, "districtId"),
    DISTRICT_NAME((short)2, "districtName"),
    PROVINCE_ID((short)3, "provinceId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DISTRICT_ID
          return DISTRICT_ID;
        case 2: // DISTRICT_NAME
          return DISTRICT_NAME;
        case 3: // PROVINCE_ID
          return PROVINCE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DISTRICTID_ISSET_ID = 0;
  private static final int __PROVINCEID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.DISTRICT_ID,_Fields.DISTRICT_NAME,_Fields.PROVINCE_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DISTRICT_ID, new org.apache.thrift.meta_data.FieldMetaData("districtId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DISTRICT_NAME, new org.apache.thrift.meta_data.FieldMetaData("districtName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROVINCE_ID, new org.apache.thrift.meta_data.FieldMetaData("provinceId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDistrict.class, metaDataMap);
  }

  public TDistrict() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDistrict(TDistrict other) {
    __isset_bitfield = other.__isset_bitfield;
    this.districtId = other.districtId;
    if (other.isSetDistrictName()) {
      this.districtName = other.districtName;
    }
    this.provinceId = other.provinceId;
  }

  public TDistrict deepCopy() {
    return new TDistrict(this);
  }

  @Override
  public void clear() {
    setDistrictIdIsSet(false);
    this.districtId = 0;
    this.districtName = null;
    setProvinceIdIsSet(false);
    this.provinceId = 0;
  }

  public int getDistrictId() {
    return this.districtId;
  }

  public TDistrict setDistrictId(int districtId) {
    this.districtId = districtId;
    setDistrictIdIsSet(true);
    return this;
  }

  public void unsetDistrictId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISTRICTID_ISSET_ID);
  }

  /** Returns true if field districtId is set (has been assigned a value) and false otherwise */
  public boolean isSetDistrictId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISTRICTID_ISSET_ID);
  }

  public void setDistrictIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISTRICTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDistrictName() {
    return this.districtName;
  }

  public TDistrict setDistrictName(@org.apache.thrift.annotation.Nullable java.lang.String districtName) {
    this.districtName = districtName;
    return this;
  }

  public void unsetDistrictName() {
    this.districtName = null;
  }

  /** Returns true if field districtName is set (has been assigned a value) and false otherwise */
  public boolean isSetDistrictName() {
    return this.districtName != null;
  }

  public void setDistrictNameIsSet(boolean value) {
    if (!value) {
      this.districtName = null;
    }
  }

  public int getProvinceId() {
    return this.provinceId;
  }

  public TDistrict setProvinceId(int provinceId) {
    this.provinceId = provinceId;
    setProvinceIdIsSet(true);
    return this;
  }

  public void unsetProvinceId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PROVINCEID_ISSET_ID);
  }

  /** Returns true if field provinceId is set (has been assigned a value) and false otherwise */
  public boolean isSetProvinceId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PROVINCEID_ISSET_ID);
  }

  public void setProvinceIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PROVINCEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DISTRICT_ID:
      if (value == null) {
        unsetDistrictId();
      } else {
        setDistrictId((java.lang.Integer)value);
      }
      break;

    case DISTRICT_NAME:
      if (value == null) {
        unsetDistrictName();
      } else {
        setDistrictName((java.lang.String)value);
      }
      break;

    case PROVINCE_ID:
      if (value == null) {
        unsetProvinceId();
      } else {
        setProvinceId((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DISTRICT_ID:
      return getDistrictId();

    case DISTRICT_NAME:
      return getDistrictName();

    case PROVINCE_ID:
      return getProvinceId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DISTRICT_ID:
      return isSetDistrictId();
    case DISTRICT_NAME:
      return isSetDistrictName();
    case PROVINCE_ID:
      return isSetProvinceId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TDistrict)
      return this.equals((TDistrict)that);
    return false;
  }

  public boolean equals(TDistrict that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_districtId = true && this.isSetDistrictId();
    boolean that_present_districtId = true && that.isSetDistrictId();
    if (this_present_districtId || that_present_districtId) {
      if (!(this_present_districtId && that_present_districtId))
        return false;
      if (this.districtId != that.districtId)
        return false;
    }

    boolean this_present_districtName = true && this.isSetDistrictName();
    boolean that_present_districtName = true && that.isSetDistrictName();
    if (this_present_districtName || that_present_districtName) {
      if (!(this_present_districtName && that_present_districtName))
        return false;
      if (!this.districtName.equals(that.districtName))
        return false;
    }

    boolean this_present_provinceId = true && this.isSetProvinceId();
    boolean that_present_provinceId = true && that.isSetProvinceId();
    if (this_present_provinceId || that_present_provinceId) {
      if (!(this_present_provinceId && that_present_provinceId))
        return false;
      if (this.provinceId != that.provinceId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDistrictId()) ? 131071 : 524287);
    if (isSetDistrictId())
      hashCode = hashCode * 8191 + districtId;

    hashCode = hashCode * 8191 + ((isSetDistrictName()) ? 131071 : 524287);
    if (isSetDistrictName())
      hashCode = hashCode * 8191 + districtName.hashCode();

    hashCode = hashCode * 8191 + ((isSetProvinceId()) ? 131071 : 524287);
    if (isSetProvinceId())
      hashCode = hashCode * 8191 + provinceId;

    return hashCode;
  }

  @Override
  public int compareTo(TDistrict other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDistrictId()).compareTo(other.isSetDistrictId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistrictId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.districtId, other.districtId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDistrictName()).compareTo(other.isSetDistrictName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistrictName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.districtName, other.districtName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProvinceId()).compareTo(other.isSetProvinceId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvinceId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provinceId, other.provinceId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TDistrict(");
    boolean first = true;

    if (isSetDistrictId()) {
      sb.append("districtId:");
      sb.append(this.districtId);
      first = false;
    }
    if (isSetDistrictName()) {
      if (!first) sb.append(", ");
      sb.append("districtName:");
      if (this.districtName == null) {
        sb.append("null");
      } else {
        sb.append(this.districtName);
      }
      first = false;
    }
    if (isSetProvinceId()) {
      if (!first) sb.append(", ");
      sb.append("provinceId:");
      sb.append(this.provinceId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDistrictStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TDistrictStandardScheme getScheme() {
      return new TDistrictStandardScheme();
    }
  }

  private static class TDistrictStandardScheme extends org.apache.thrift.scheme.StandardScheme<TDistrict> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDistrict struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DISTRICT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.districtId = iprot.readI32();
              struct.setDistrictIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DISTRICT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.districtName = iprot.readString();
              struct.setDistrictNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROVINCE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.provinceId = iprot.readI32();
              struct.setProvinceIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDistrict struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetDistrictId()) {
        oprot.writeFieldBegin(DISTRICT_ID_FIELD_DESC);
        oprot.writeI32(struct.districtId);
        oprot.writeFieldEnd();
      }
      if (struct.districtName != null) {
        if (struct.isSetDistrictName()) {
          oprot.writeFieldBegin(DISTRICT_NAME_FIELD_DESC);
          oprot.writeString(struct.districtName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetProvinceId()) {
        oprot.writeFieldBegin(PROVINCE_ID_FIELD_DESC);
        oprot.writeI32(struct.provinceId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDistrictTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TDistrictTupleScheme getScheme() {
      return new TDistrictTupleScheme();
    }
  }

  private static class TDistrictTupleScheme extends org.apache.thrift.scheme.TupleScheme<TDistrict> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDistrict struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDistrictId()) {
        optionals.set(0);
      }
      if (struct.isSetDistrictName()) {
        optionals.set(1);
      }
      if (struct.isSetProvinceId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetDistrictId()) {
        oprot.writeI32(struct.districtId);
      }
      if (struct.isSetDistrictName()) {
        oprot.writeString(struct.districtName);
      }
      if (struct.isSetProvinceId()) {
        oprot.writeI32(struct.provinceId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDistrict struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.districtId = iprot.readI32();
        struct.setDistrictIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.districtName = iprot.readString();
        struct.setDistrictNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.provinceId = iprot.readI32();
        struct.setProvinceIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

