/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-28")
public class TFeatureRequest implements org.apache.thrift.TBase<TFeatureRequest, TFeatureRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TFeatureRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TFeatureRequest");

  private static final org.apache.thrift.protocol.TField NAME_FEATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("nameFeature", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TFeatureRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TFeatureRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String nameFeature; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME_FEATURE((short)1, "nameFeature");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME_FEATURE
          return NAME_FEATURE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME_FEATURE, new org.apache.thrift.meta_data.FieldMetaData("nameFeature", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TFeatureRequest.class, metaDataMap);
  }

  public TFeatureRequest() {
  }

  public TFeatureRequest(
    java.lang.String nameFeature)
  {
    this();
    this.nameFeature = nameFeature;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TFeatureRequest(TFeatureRequest other) {
    if (other.isSetNameFeature()) {
      this.nameFeature = other.nameFeature;
    }
  }

  public TFeatureRequest deepCopy() {
    return new TFeatureRequest(this);
  }

  @Override
  public void clear() {
    this.nameFeature = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNameFeature() {
    return this.nameFeature;
  }

  public TFeatureRequest setNameFeature(@org.apache.thrift.annotation.Nullable java.lang.String nameFeature) {
    this.nameFeature = nameFeature;
    return this;
  }

  public void unsetNameFeature() {
    this.nameFeature = null;
  }

  /** Returns true if field nameFeature is set (has been assigned a value) and false otherwise */
  public boolean isSetNameFeature() {
    return this.nameFeature != null;
  }

  public void setNameFeatureIsSet(boolean value) {
    if (!value) {
      this.nameFeature = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NAME_FEATURE:
      if (value == null) {
        unsetNameFeature();
      } else {
        setNameFeature((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME_FEATURE:
      return getNameFeature();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NAME_FEATURE:
      return isSetNameFeature();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TFeatureRequest)
      return this.equals((TFeatureRequest)that);
    return false;
  }

  public boolean equals(TFeatureRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_nameFeature = true && this.isSetNameFeature();
    boolean that_present_nameFeature = true && that.isSetNameFeature();
    if (this_present_nameFeature || that_present_nameFeature) {
      if (!(this_present_nameFeature && that_present_nameFeature))
        return false;
      if (!this.nameFeature.equals(that.nameFeature))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNameFeature()) ? 131071 : 524287);
    if (isSetNameFeature())
      hashCode = hashCode * 8191 + nameFeature.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TFeatureRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNameFeature()).compareTo(other.isSetNameFeature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNameFeature()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nameFeature, other.nameFeature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TFeatureRequest(");
    boolean first = true;

    sb.append("nameFeature:");
    if (this.nameFeature == null) {
      sb.append("null");
    } else {
      sb.append(this.nameFeature);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (nameFeature == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'nameFeature' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TFeatureRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFeatureRequestStandardScheme getScheme() {
      return new TFeatureRequestStandardScheme();
    }
  }

  private static class TFeatureRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TFeatureRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TFeatureRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME_FEATURE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nameFeature = iprot.readString();
              struct.setNameFeatureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TFeatureRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.nameFeature != null) {
        oprot.writeFieldBegin(NAME_FEATURE_FIELD_DESC);
        oprot.writeString(struct.nameFeature);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TFeatureRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFeatureRequestTupleScheme getScheme() {
      return new TFeatureRequestTupleScheme();
    }
  }

  private static class TFeatureRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TFeatureRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TFeatureRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.nameFeature);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TFeatureRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.nameFeature = iprot.readString();
      struct.setNameFeatureIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

