/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-28")
public class TFeedBackRequest implements org.apache.thrift.TBase<TFeedBackRequest, TFeedBackRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TFeedBackRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TFeedBackRequest");

  private static final org.apache.thrift.protocol.TField COMMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("comment", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SENDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("senderId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField POINT_STAR_FIELD_DESC = new org.apache.thrift.protocol.TField("pointStar", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField RECEIVER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("receiverId", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TFeedBackRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TFeedBackRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String comment; // required
  public int senderId; // required
  public int pointStar; // required
  public int receiverId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMMENT((short)1, "comment"),
    SENDER_ID((short)2, "senderId"),
    POINT_STAR((short)3, "pointStar"),
    RECEIVER_ID((short)4, "receiverId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COMMENT
          return COMMENT;
        case 2: // SENDER_ID
          return SENDER_ID;
        case 3: // POINT_STAR
          return POINT_STAR;
        case 4: // RECEIVER_ID
          return RECEIVER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SENDERID_ISSET_ID = 0;
  private static final int __POINTSTAR_ISSET_ID = 1;
  private static final int __RECEIVERID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMMENT, new org.apache.thrift.meta_data.FieldMetaData("comment", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SENDER_ID, new org.apache.thrift.meta_data.FieldMetaData("senderId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.POINT_STAR, new org.apache.thrift.meta_data.FieldMetaData("pointStar", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RECEIVER_ID, new org.apache.thrift.meta_data.FieldMetaData("receiverId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TFeedBackRequest.class, metaDataMap);
  }

  public TFeedBackRequest() {
  }

  public TFeedBackRequest(
    java.lang.String comment,
    int senderId,
    int pointStar,
    int receiverId)
  {
    this();
    this.comment = comment;
    this.senderId = senderId;
    setSenderIdIsSet(true);
    this.pointStar = pointStar;
    setPointStarIsSet(true);
    this.receiverId = receiverId;
    setReceiverIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TFeedBackRequest(TFeedBackRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetComment()) {
      this.comment = other.comment;
    }
    this.senderId = other.senderId;
    this.pointStar = other.pointStar;
    this.receiverId = other.receiverId;
  }

  public TFeedBackRequest deepCopy() {
    return new TFeedBackRequest(this);
  }

  @Override
  public void clear() {
    this.comment = null;
    setSenderIdIsSet(false);
    this.senderId = 0;
    setPointStarIsSet(false);
    this.pointStar = 0;
    setReceiverIdIsSet(false);
    this.receiverId = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getComment() {
    return this.comment;
  }

  public TFeedBackRequest setComment(@org.apache.thrift.annotation.Nullable java.lang.String comment) {
    this.comment = comment;
    return this;
  }

  public void unsetComment() {
    this.comment = null;
  }

  /** Returns true if field comment is set (has been assigned a value) and false otherwise */
  public boolean isSetComment() {
    return this.comment != null;
  }

  public void setCommentIsSet(boolean value) {
    if (!value) {
      this.comment = null;
    }
  }

  public int getSenderId() {
    return this.senderId;
  }

  public TFeedBackRequest setSenderId(int senderId) {
    this.senderId = senderId;
    setSenderIdIsSet(true);
    return this;
  }

  public void unsetSenderId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SENDERID_ISSET_ID);
  }

  /** Returns true if field senderId is set (has been assigned a value) and false otherwise */
  public boolean isSetSenderId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SENDERID_ISSET_ID);
  }

  public void setSenderIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SENDERID_ISSET_ID, value);
  }

  public int getPointStar() {
    return this.pointStar;
  }

  public TFeedBackRequest setPointStar(int pointStar) {
    this.pointStar = pointStar;
    setPointStarIsSet(true);
    return this;
  }

  public void unsetPointStar() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __POINTSTAR_ISSET_ID);
  }

  /** Returns true if field pointStar is set (has been assigned a value) and false otherwise */
  public boolean isSetPointStar() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __POINTSTAR_ISSET_ID);
  }

  public void setPointStarIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __POINTSTAR_ISSET_ID, value);
  }

  public int getReceiverId() {
    return this.receiverId;
  }

  public TFeedBackRequest setReceiverId(int receiverId) {
    this.receiverId = receiverId;
    setReceiverIdIsSet(true);
    return this;
  }

  public void unsetReceiverId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RECEIVERID_ISSET_ID);
  }

  /** Returns true if field receiverId is set (has been assigned a value) and false otherwise */
  public boolean isSetReceiverId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RECEIVERID_ISSET_ID);
  }

  public void setReceiverIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RECEIVERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case COMMENT:
      if (value == null) {
        unsetComment();
      } else {
        setComment((java.lang.String)value);
      }
      break;

    case SENDER_ID:
      if (value == null) {
        unsetSenderId();
      } else {
        setSenderId((java.lang.Integer)value);
      }
      break;

    case POINT_STAR:
      if (value == null) {
        unsetPointStar();
      } else {
        setPointStar((java.lang.Integer)value);
      }
      break;

    case RECEIVER_ID:
      if (value == null) {
        unsetReceiverId();
      } else {
        setReceiverId((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case COMMENT:
      return getComment();

    case SENDER_ID:
      return getSenderId();

    case POINT_STAR:
      return getPointStar();

    case RECEIVER_ID:
      return getReceiverId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case COMMENT:
      return isSetComment();
    case SENDER_ID:
      return isSetSenderId();
    case POINT_STAR:
      return isSetPointStar();
    case RECEIVER_ID:
      return isSetReceiverId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TFeedBackRequest)
      return this.equals((TFeedBackRequest)that);
    return false;
  }

  public boolean equals(TFeedBackRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_comment = true && this.isSetComment();
    boolean that_present_comment = true && that.isSetComment();
    if (this_present_comment || that_present_comment) {
      if (!(this_present_comment && that_present_comment))
        return false;
      if (!this.comment.equals(that.comment))
        return false;
    }

    boolean this_present_senderId = true;
    boolean that_present_senderId = true;
    if (this_present_senderId || that_present_senderId) {
      if (!(this_present_senderId && that_present_senderId))
        return false;
      if (this.senderId != that.senderId)
        return false;
    }

    boolean this_present_pointStar = true;
    boolean that_present_pointStar = true;
    if (this_present_pointStar || that_present_pointStar) {
      if (!(this_present_pointStar && that_present_pointStar))
        return false;
      if (this.pointStar != that.pointStar)
        return false;
    }

    boolean this_present_receiverId = true;
    boolean that_present_receiverId = true;
    if (this_present_receiverId || that_present_receiverId) {
      if (!(this_present_receiverId && that_present_receiverId))
        return false;
      if (this.receiverId != that.receiverId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetComment()) ? 131071 : 524287);
    if (isSetComment())
      hashCode = hashCode * 8191 + comment.hashCode();

    hashCode = hashCode * 8191 + senderId;

    hashCode = hashCode * 8191 + pointStar;

    hashCode = hashCode * 8191 + receiverId;

    return hashCode;
  }

  @Override
  public int compareTo(TFeedBackRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetComment()).compareTo(other.isSetComment());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetComment()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.comment, other.comment);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSenderId()).compareTo(other.isSetSenderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSenderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.senderId, other.senderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPointStar()).compareTo(other.isSetPointStar());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPointStar()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pointStar, other.pointStar);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReceiverId()).compareTo(other.isSetReceiverId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReceiverId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.receiverId, other.receiverId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TFeedBackRequest(");
    boolean first = true;

    sb.append("comment:");
    if (this.comment == null) {
      sb.append("null");
    } else {
      sb.append(this.comment);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("senderId:");
    sb.append(this.senderId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pointStar:");
    sb.append(this.pointStar);
    first = false;
    if (!first) sb.append(", ");
    sb.append("receiverId:");
    sb.append(this.receiverId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (comment == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'comment' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'senderId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pointStar' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'receiverId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TFeedBackRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFeedBackRequestStandardScheme getScheme() {
      return new TFeedBackRequestStandardScheme();
    }
  }

  private static class TFeedBackRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TFeedBackRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TFeedBackRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COMMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.comment = iprot.readString();
              struct.setCommentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SENDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.senderId = iprot.readI32();
              struct.setSenderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // POINT_STAR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pointStar = iprot.readI32();
              struct.setPointStarIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // RECEIVER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.receiverId = iprot.readI32();
              struct.setReceiverIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetSenderId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'senderId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPointStar()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pointStar' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetReceiverId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'receiverId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TFeedBackRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.comment != null) {
        oprot.writeFieldBegin(COMMENT_FIELD_DESC);
        oprot.writeString(struct.comment);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SENDER_ID_FIELD_DESC);
      oprot.writeI32(struct.senderId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POINT_STAR_FIELD_DESC);
      oprot.writeI32(struct.pointStar);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RECEIVER_ID_FIELD_DESC);
      oprot.writeI32(struct.receiverId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TFeedBackRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFeedBackRequestTupleScheme getScheme() {
      return new TFeedBackRequestTupleScheme();
    }
  }

  private static class TFeedBackRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TFeedBackRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TFeedBackRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.comment);
      oprot.writeI32(struct.senderId);
      oprot.writeI32(struct.pointStar);
      oprot.writeI32(struct.receiverId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TFeedBackRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.comment = iprot.readString();
      struct.setCommentIsSet(true);
      struct.senderId = iprot.readI32();
      struct.setSenderIdIsSet(true);
      struct.pointStar = iprot.readI32();
      struct.setPointStarIsSet(true);
      struct.receiverId = iprot.readI32();
      struct.setReceiverIdIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

