/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-09-30")
public enum TTypeFuel implements org.apache.thrift.TEnum {
  T_GAS(1),
  T_DIESEL(2),
  T_ELECTRIC(3);

  private final int value;

  private TTypeFuel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TTypeFuel findByValue(int value) { 
    switch (value) {
      case 1:
        return T_GAS;
      case 2:
        return T_DIESEL;
      case 3:
        return T_ELECTRIC;
      default:
        return null;
    }
  }
}
