/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-10-08")
public class TUserRole implements org.apache.thrift.TBase<TUserRole, TUserRole._Fields>, java.io.Serializable, Cloneable, Comparable<TUserRole> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TUserRole");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField ROLE_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("roleIds", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField IS_SUPER_ADMIN_FIELD_DESC = new org.apache.thrift.protocol.TField("isSuperAdmin", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField ROLES_FIELD_DESC = new org.apache.thrift.protocol.TField("roles", org.apache.thrift.protocol.TType.LIST, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TUserRoleStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TUserRoleTupleSchemeFactory();

  public int id; // optional
  public int userId; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> roleIds; // optional
  public boolean isSuperAdmin; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<TRole> roles; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    USER_ID((short)2, "userId"),
    ROLE_IDS((short)3, "roleIds"),
    IS_SUPER_ADMIN((short)4, "isSuperAdmin"),
    ROLES((short)5, "roles");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // USER_ID
          return USER_ID;
        case 3: // ROLE_IDS
          return ROLE_IDS;
        case 4: // IS_SUPER_ADMIN
          return IS_SUPER_ADMIN;
        case 5: // ROLES
          return ROLES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __USERID_ISSET_ID = 1;
  private static final int __ISSUPERADMIN_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.ID,_Fields.USER_ID,_Fields.ROLE_IDS,_Fields.IS_SUPER_ADMIN,_Fields.ROLES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ROLE_IDS, new org.apache.thrift.meta_data.FieldMetaData("roleIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.IS_SUPER_ADMIN, new org.apache.thrift.meta_data.FieldMetaData("isSuperAdmin", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ROLES, new org.apache.thrift.meta_data.FieldMetaData("roles", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TRole.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TUserRole.class, metaDataMap);
  }

  public TUserRole() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TUserRole(TUserRole other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.userId = other.userId;
    if (other.isSetRoleIds()) {
      java.util.List<java.lang.Integer> __this__roleIds = new java.util.ArrayList<java.lang.Integer>(other.roleIds);
      this.roleIds = __this__roleIds;
    }
    this.isSuperAdmin = other.isSuperAdmin;
    if (other.isSetRoles()) {
      java.util.List<TRole> __this__roles = new java.util.ArrayList<TRole>(other.roles.size());
      for (TRole other_element : other.roles) {
        __this__roles.add(new TRole(other_element));
      }
      this.roles = __this__roles;
    }
  }

  public TUserRole deepCopy() {
    return new TUserRole(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setUserIdIsSet(false);
    this.userId = 0;
    this.roleIds = null;
    setIsSuperAdminIsSet(false);
    this.isSuperAdmin = false;
    this.roles = null;
  }

  public int getId() {
    return this.id;
  }

  public TUserRole setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getUserId() {
    return this.userId;
  }

  public TUserRole setUserId(int userId) {
    this.userId = userId;
    setUserIdIsSet(true);
    return this;
  }

  public void unsetUserId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public int getRoleIdsSize() {
    return (this.roleIds == null) ? 0 : this.roleIds.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getRoleIdsIterator() {
    return (this.roleIds == null) ? null : this.roleIds.iterator();
  }

  public void addToRoleIds(int elem) {
    if (this.roleIds == null) {
      this.roleIds = new java.util.ArrayList<java.lang.Integer>();
    }
    this.roleIds.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Integer> getRoleIds() {
    return this.roleIds;
  }

  public TUserRole setRoleIds(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> roleIds) {
    this.roleIds = roleIds;
    return this;
  }

  public void unsetRoleIds() {
    this.roleIds = null;
  }

  /** Returns true if field roleIds is set (has been assigned a value) and false otherwise */
  public boolean isSetRoleIds() {
    return this.roleIds != null;
  }

  public void setRoleIdsIsSet(boolean value) {
    if (!value) {
      this.roleIds = null;
    }
  }

  public boolean isIsSuperAdmin() {
    return this.isSuperAdmin;
  }

  public TUserRole setIsSuperAdmin(boolean isSuperAdmin) {
    this.isSuperAdmin = isSuperAdmin;
    setIsSuperAdminIsSet(true);
    return this;
  }

  public void unsetIsSuperAdmin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISSUPERADMIN_ISSET_ID);
  }

  /** Returns true if field isSuperAdmin is set (has been assigned a value) and false otherwise */
  public boolean isSetIsSuperAdmin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISSUPERADMIN_ISSET_ID);
  }

  public void setIsSuperAdminIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISSUPERADMIN_ISSET_ID, value);
  }

  public int getRolesSize() {
    return (this.roles == null) ? 0 : this.roles.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TRole> getRolesIterator() {
    return (this.roles == null) ? null : this.roles.iterator();
  }

  public void addToRoles(TRole elem) {
    if (this.roles == null) {
      this.roles = new java.util.ArrayList<TRole>();
    }
    this.roles.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TRole> getRoles() {
    return this.roles;
  }

  public TUserRole setRoles(@org.apache.thrift.annotation.Nullable java.util.List<TRole> roles) {
    this.roles = roles;
    return this;
  }

  public void unsetRoles() {
    this.roles = null;
  }

  /** Returns true if field roles is set (has been assigned a value) and false otherwise */
  public boolean isSetRoles() {
    return this.roles != null;
  }

  public void setRolesIsSet(boolean value) {
    if (!value) {
      this.roles = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((java.lang.Integer)value);
      }
      break;

    case ROLE_IDS:
      if (value == null) {
        unsetRoleIds();
      } else {
        setRoleIds((java.util.List<java.lang.Integer>)value);
      }
      break;

    case IS_SUPER_ADMIN:
      if (value == null) {
        unsetIsSuperAdmin();
      } else {
        setIsSuperAdmin((java.lang.Boolean)value);
      }
      break;

    case ROLES:
      if (value == null) {
        unsetRoles();
      } else {
        setRoles((java.util.List<TRole>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case USER_ID:
      return getUserId();

    case ROLE_IDS:
      return getRoleIds();

    case IS_SUPER_ADMIN:
      return isIsSuperAdmin();

    case ROLES:
      return getRoles();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case USER_ID:
      return isSetUserId();
    case ROLE_IDS:
      return isSetRoleIds();
    case IS_SUPER_ADMIN:
      return isSetIsSuperAdmin();
    case ROLES:
      return isSetRoles();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TUserRole)
      return this.equals((TUserRole)that);
    return false;
  }

  public boolean equals(TUserRole that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_userId = true && this.isSetUserId();
    boolean that_present_userId = true && that.isSetUserId();
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (this.userId != that.userId)
        return false;
    }

    boolean this_present_roleIds = true && this.isSetRoleIds();
    boolean that_present_roleIds = true && that.isSetRoleIds();
    if (this_present_roleIds || that_present_roleIds) {
      if (!(this_present_roleIds && that_present_roleIds))
        return false;
      if (!this.roleIds.equals(that.roleIds))
        return false;
    }

    boolean this_present_isSuperAdmin = true && this.isSetIsSuperAdmin();
    boolean that_present_isSuperAdmin = true && that.isSetIsSuperAdmin();
    if (this_present_isSuperAdmin || that_present_isSuperAdmin) {
      if (!(this_present_isSuperAdmin && that_present_isSuperAdmin))
        return false;
      if (this.isSuperAdmin != that.isSuperAdmin)
        return false;
    }

    boolean this_present_roles = true && this.isSetRoles();
    boolean that_present_roles = true && that.isSetRoles();
    if (this_present_roles || that_present_roles) {
      if (!(this_present_roles && that_present_roles))
        return false;
      if (!this.roles.equals(that.roles))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetUserId()) ? 131071 : 524287);
    if (isSetUserId())
      hashCode = hashCode * 8191 + userId;

    hashCode = hashCode * 8191 + ((isSetRoleIds()) ? 131071 : 524287);
    if (isSetRoleIds())
      hashCode = hashCode * 8191 + roleIds.hashCode();

    hashCode = hashCode * 8191 + ((isSetIsSuperAdmin()) ? 131071 : 524287);
    if (isSetIsSuperAdmin())
      hashCode = hashCode * 8191 + ((isSuperAdmin) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetRoles()) ? 131071 : 524287);
    if (isSetRoles())
      hashCode = hashCode * 8191 + roles.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TUserRole other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRoleIds()).compareTo(other.isSetRoleIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoleIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roleIds, other.roleIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIsSuperAdmin()).compareTo(other.isSetIsSuperAdmin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsSuperAdmin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isSuperAdmin, other.isSuperAdmin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRoles()).compareTo(other.isSetRoles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roles, other.roles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TUserRole(");
    boolean first = true;

    if (isSetId()) {
      sb.append("id:");
      sb.append(this.id);
      first = false;
    }
    if (isSetUserId()) {
      if (!first) sb.append(", ");
      sb.append("userId:");
      sb.append(this.userId);
      first = false;
    }
    if (isSetRoleIds()) {
      if (!first) sb.append(", ");
      sb.append("roleIds:");
      if (this.roleIds == null) {
        sb.append("null");
      } else {
        sb.append(this.roleIds);
      }
      first = false;
    }
    if (isSetIsSuperAdmin()) {
      if (!first) sb.append(", ");
      sb.append("isSuperAdmin:");
      sb.append(this.isSuperAdmin);
      first = false;
    }
    if (isSetRoles()) {
      if (!first) sb.append(", ");
      sb.append("roles:");
      if (this.roles == null) {
        sb.append("null");
      } else {
        sb.append(this.roles);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TUserRoleStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TUserRoleStandardScheme getScheme() {
      return new TUserRoleStandardScheme();
    }
  }

  private static class TUserRoleStandardScheme extends org.apache.thrift.scheme.StandardScheme<TUserRole> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TUserRole struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userId = iprot.readI32();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROLE_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list120 = iprot.readListBegin();
                struct.roleIds = new java.util.ArrayList<java.lang.Integer>(_list120.size);
                int _elem121;
                for (int _i122 = 0; _i122 < _list120.size; ++_i122)
                {
                  _elem121 = iprot.readI32();
                  struct.roleIds.add(_elem121);
                }
                iprot.readListEnd();
              }
              struct.setRoleIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_SUPER_ADMIN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isSuperAdmin = iprot.readBool();
              struct.setIsSuperAdminIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ROLES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list123 = iprot.readListBegin();
                struct.roles = new java.util.ArrayList<TRole>(_list123.size);
                @org.apache.thrift.annotation.Nullable TRole _elem124;
                for (int _i125 = 0; _i125 < _list123.size; ++_i125)
                {
                  _elem124 = new TRole();
                  _elem124.read(iprot);
                  struct.roles.add(_elem124);
                }
                iprot.readListEnd();
              }
              struct.setRolesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TUserRole struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetId()) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeI32(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUserId()) {
        oprot.writeFieldBegin(USER_ID_FIELD_DESC);
        oprot.writeI32(struct.userId);
        oprot.writeFieldEnd();
      }
      if (struct.roleIds != null) {
        if (struct.isSetRoleIds()) {
          oprot.writeFieldBegin(ROLE_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.roleIds.size()));
            for (int _iter126 : struct.roleIds)
            {
              oprot.writeI32(_iter126);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetIsSuperAdmin()) {
        oprot.writeFieldBegin(IS_SUPER_ADMIN_FIELD_DESC);
        oprot.writeBool(struct.isSuperAdmin);
        oprot.writeFieldEnd();
      }
      if (struct.roles != null) {
        if (struct.isSetRoles()) {
          oprot.writeFieldBegin(ROLES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.roles.size()));
            for (TRole _iter127 : struct.roles)
            {
              _iter127.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TUserRoleTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TUserRoleTupleScheme getScheme() {
      return new TUserRoleTupleScheme();
    }
  }

  private static class TUserRoleTupleScheme extends org.apache.thrift.scheme.TupleScheme<TUserRole> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TUserRole struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetUserId()) {
        optionals.set(1);
      }
      if (struct.isSetRoleIds()) {
        optionals.set(2);
      }
      if (struct.isSetIsSuperAdmin()) {
        optionals.set(3);
      }
      if (struct.isSetRoles()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetUserId()) {
        oprot.writeI32(struct.userId);
      }
      if (struct.isSetRoleIds()) {
        {
          oprot.writeI32(struct.roleIds.size());
          for (int _iter128 : struct.roleIds)
          {
            oprot.writeI32(_iter128);
          }
        }
      }
      if (struct.isSetIsSuperAdmin()) {
        oprot.writeBool(struct.isSuperAdmin);
      }
      if (struct.isSetRoles()) {
        {
          oprot.writeI32(struct.roles.size());
          for (TRole _iter129 : struct.roles)
          {
            _iter129.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TUserRole struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.userId = iprot.readI32();
        struct.setUserIdIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list130 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.roleIds = new java.util.ArrayList<java.lang.Integer>(_list130.size);
          int _elem131;
          for (int _i132 = 0; _i132 < _list130.size; ++_i132)
          {
            _elem131 = iprot.readI32();
            struct.roleIds.add(_elem131);
          }
        }
        struct.setRoleIdsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.isSuperAdmin = iprot.readBool();
        struct.setIsSuperAdminIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list133 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.roles = new java.util.ArrayList<TRole>(_list133.size);
          @org.apache.thrift.annotation.Nullable TRole _elem134;
          for (int _i135 = 0; _i135 < _list133.size; ++_i135)
          {
            _elem134 = new TRole();
            _elem134.read(iprot);
            struct.roles.add(_elem134);
          }
        }
        struct.setRolesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

