/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-10-07")
public class TVoucher implements org.apache.thrift.TBase<TVoucher, TVoucher._Fields>, java.io.Serializable, Cloneable, Comparable<TVoucher> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TVoucher");

  private static final org.apache.thrift.protocol.TField VOUCHER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("voucherId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("title", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IMAGE_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("imageUrl", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PUBLIC_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("publicId", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("body", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField DISCOUNT_PERCENT_FIELD_DESC = new org.apache.thrift.protocol.TField("discountPercent", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField MAX_DISCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("maxDiscount", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField START_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("startDate", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField END_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("endDate", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField CREATED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("createdAt", org.apache.thrift.protocol.TType.I64, (short)20);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TVoucherStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TVoucherTupleSchemeFactory();

  public int voucherId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String title; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String code; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String imageUrl; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String publicId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String body; // optional
  public int discountPercent; // optional
  public long maxDiscount; // optional
  public long startDate; // optional
  public long endDate; // optional
  public long createdAt; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VOUCHER_ID((short)1, "voucherId"),
    TITLE((short)2, "title"),
    CODE((short)3, "code"),
    IMAGE_URL((short)4, "imageUrl"),
    PUBLIC_ID((short)5, "publicId"),
    BODY((short)6, "body"),
    DISCOUNT_PERCENT((short)7, "discountPercent"),
    MAX_DISCOUNT((short)8, "maxDiscount"),
    START_DATE((short)9, "startDate"),
    END_DATE((short)10, "endDate"),
    CREATED_AT((short)20, "createdAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VOUCHER_ID
          return VOUCHER_ID;
        case 2: // TITLE
          return TITLE;
        case 3: // CODE
          return CODE;
        case 4: // IMAGE_URL
          return IMAGE_URL;
        case 5: // PUBLIC_ID
          return PUBLIC_ID;
        case 6: // BODY
          return BODY;
        case 7: // DISCOUNT_PERCENT
          return DISCOUNT_PERCENT;
        case 8: // MAX_DISCOUNT
          return MAX_DISCOUNT;
        case 9: // START_DATE
          return START_DATE;
        case 10: // END_DATE
          return END_DATE;
        case 20: // CREATED_AT
          return CREATED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VOUCHERID_ISSET_ID = 0;
  private static final int __DISCOUNTPERCENT_ISSET_ID = 1;
  private static final int __MAXDISCOUNT_ISSET_ID = 2;
  private static final int __STARTDATE_ISSET_ID = 3;
  private static final int __ENDDATE_ISSET_ID = 4;
  private static final int __CREATEDAT_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.VOUCHER_ID,_Fields.TITLE,_Fields.CODE,_Fields.IMAGE_URL,_Fields.PUBLIC_ID,_Fields.BODY,_Fields.DISCOUNT_PERCENT,_Fields.MAX_DISCOUNT,_Fields.START_DATE,_Fields.END_DATE,_Fields.CREATED_AT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VOUCHER_ID, new org.apache.thrift.meta_data.FieldMetaData("voucherId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TITLE, new org.apache.thrift.meta_data.FieldMetaData("title", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMAGE_URL, new org.apache.thrift.meta_data.FieldMetaData("imageUrl", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PUBLIC_ID, new org.apache.thrift.meta_data.FieldMetaData("publicId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BODY, new org.apache.thrift.meta_data.FieldMetaData("body", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISCOUNT_PERCENT, new org.apache.thrift.meta_data.FieldMetaData("discountPercent", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAX_DISCOUNT, new org.apache.thrift.meta_data.FieldMetaData("maxDiscount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.START_DATE, new org.apache.thrift.meta_data.FieldMetaData("startDate", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_DATE, new org.apache.thrift.meta_data.FieldMetaData("endDate", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATED_AT, new org.apache.thrift.meta_data.FieldMetaData("createdAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TVoucher.class, metaDataMap);
  }

  public TVoucher() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TVoucher(TVoucher other) {
    __isset_bitfield = other.__isset_bitfield;
    this.voucherId = other.voucherId;
    if (other.isSetTitle()) {
      this.title = other.title;
    }
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetImageUrl()) {
      this.imageUrl = other.imageUrl;
    }
    if (other.isSetPublicId()) {
      this.publicId = other.publicId;
    }
    if (other.isSetBody()) {
      this.body = other.body;
    }
    this.discountPercent = other.discountPercent;
    this.maxDiscount = other.maxDiscount;
    this.startDate = other.startDate;
    this.endDate = other.endDate;
    this.createdAt = other.createdAt;
  }

  public TVoucher deepCopy() {
    return new TVoucher(this);
  }

  @Override
  public void clear() {
    setVoucherIdIsSet(false);
    this.voucherId = 0;
    this.title = null;
    this.code = null;
    this.imageUrl = null;
    this.publicId = null;
    this.body = null;
    setDiscountPercentIsSet(false);
    this.discountPercent = 0;
    setMaxDiscountIsSet(false);
    this.maxDiscount = 0;
    setStartDateIsSet(false);
    this.startDate = 0;
    setEndDateIsSet(false);
    this.endDate = 0;
    setCreatedAtIsSet(false);
    this.createdAt = 0;
  }

  public int getVoucherId() {
    return this.voucherId;
  }

  public TVoucher setVoucherId(int voucherId) {
    this.voucherId = voucherId;
    setVoucherIdIsSet(true);
    return this;
  }

  public void unsetVoucherId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VOUCHERID_ISSET_ID);
  }

  /** Returns true if field voucherId is set (has been assigned a value) and false otherwise */
  public boolean isSetVoucherId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VOUCHERID_ISSET_ID);
  }

  public void setVoucherIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VOUCHERID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTitle() {
    return this.title;
  }

  public TVoucher setTitle(@org.apache.thrift.annotation.Nullable java.lang.String title) {
    this.title = title;
    return this;
  }

  public void unsetTitle() {
    this.title = null;
  }

  /** Returns true if field title is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle() {
    return this.title != null;
  }

  public void setTitleIsSet(boolean value) {
    if (!value) {
      this.title = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCode() {
    return this.code;
  }

  public TVoucher setCode(@org.apache.thrift.annotation.Nullable java.lang.String code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getImageUrl() {
    return this.imageUrl;
  }

  public TVoucher setImageUrl(@org.apache.thrift.annotation.Nullable java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  public void unsetImageUrl() {
    this.imageUrl = null;
  }

  /** Returns true if field imageUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetImageUrl() {
    return this.imageUrl != null;
  }

  public void setImageUrlIsSet(boolean value) {
    if (!value) {
      this.imageUrl = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPublicId() {
    return this.publicId;
  }

  public TVoucher setPublicId(@org.apache.thrift.annotation.Nullable java.lang.String publicId) {
    this.publicId = publicId;
    return this;
  }

  public void unsetPublicId() {
    this.publicId = null;
  }

  /** Returns true if field publicId is set (has been assigned a value) and false otherwise */
  public boolean isSetPublicId() {
    return this.publicId != null;
  }

  public void setPublicIdIsSet(boolean value) {
    if (!value) {
      this.publicId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBody() {
    return this.body;
  }

  public TVoucher setBody(@org.apache.thrift.annotation.Nullable java.lang.String body) {
    this.body = body;
    return this;
  }

  public void unsetBody() {
    this.body = null;
  }

  /** Returns true if field body is set (has been assigned a value) and false otherwise */
  public boolean isSetBody() {
    return this.body != null;
  }

  public void setBodyIsSet(boolean value) {
    if (!value) {
      this.body = null;
    }
  }

  public int getDiscountPercent() {
    return this.discountPercent;
  }

  public TVoucher setDiscountPercent(int discountPercent) {
    this.discountPercent = discountPercent;
    setDiscountPercentIsSet(true);
    return this;
  }

  public void unsetDiscountPercent() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID);
  }

  /** Returns true if field discountPercent is set (has been assigned a value) and false otherwise */
  public boolean isSetDiscountPercent() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID);
  }

  public void setDiscountPercentIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID, value);
  }

  public long getMaxDiscount() {
    return this.maxDiscount;
  }

  public TVoucher setMaxDiscount(long maxDiscount) {
    this.maxDiscount = maxDiscount;
    setMaxDiscountIsSet(true);
    return this;
  }

  public void unsetMaxDiscount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID);
  }

  /** Returns true if field maxDiscount is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxDiscount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID);
  }

  public void setMaxDiscountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID, value);
  }

  public long getStartDate() {
    return this.startDate;
  }

  public TVoucher setStartDate(long startDate) {
    this.startDate = startDate;
    setStartDateIsSet(true);
    return this;
  }

  public void unsetStartDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  /** Returns true if field startDate is set (has been assigned a value) and false otherwise */
  public boolean isSetStartDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  public void setStartDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTDATE_ISSET_ID, value);
  }

  public long getEndDate() {
    return this.endDate;
  }

  public TVoucher setEndDate(long endDate) {
    this.endDate = endDate;
    setEndDateIsSet(true);
    return this;
  }

  public void unsetEndDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  /** Returns true if field endDate is set (has been assigned a value) and false otherwise */
  public boolean isSetEndDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  public void setEndDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDDATE_ISSET_ID, value);
  }

  public long getCreatedAt() {
    return this.createdAt;
  }

  public TVoucher setCreatedAt(long createdAt) {
    this.createdAt = createdAt;
    setCreatedAtIsSet(true);
    return this;
  }

  public void unsetCreatedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  /** Returns true if field createdAt is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  public void setCreatedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEDAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case VOUCHER_ID:
      if (value == null) {
        unsetVoucherId();
      } else {
        setVoucherId((java.lang.Integer)value);
      }
      break;

    case TITLE:
      if (value == null) {
        unsetTitle();
      } else {
        setTitle((java.lang.String)value);
      }
      break;

    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((java.lang.String)value);
      }
      break;

    case IMAGE_URL:
      if (value == null) {
        unsetImageUrl();
      } else {
        setImageUrl((java.lang.String)value);
      }
      break;

    case PUBLIC_ID:
      if (value == null) {
        unsetPublicId();
      } else {
        setPublicId((java.lang.String)value);
      }
      break;

    case BODY:
      if (value == null) {
        unsetBody();
      } else {
        setBody((java.lang.String)value);
      }
      break;

    case DISCOUNT_PERCENT:
      if (value == null) {
        unsetDiscountPercent();
      } else {
        setDiscountPercent((java.lang.Integer)value);
      }
      break;

    case MAX_DISCOUNT:
      if (value == null) {
        unsetMaxDiscount();
      } else {
        setMaxDiscount((java.lang.Long)value);
      }
      break;

    case START_DATE:
      if (value == null) {
        unsetStartDate();
      } else {
        setStartDate((java.lang.Long)value);
      }
      break;

    case END_DATE:
      if (value == null) {
        unsetEndDate();
      } else {
        setEndDate((java.lang.Long)value);
      }
      break;

    case CREATED_AT:
      if (value == null) {
        unsetCreatedAt();
      } else {
        setCreatedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VOUCHER_ID:
      return getVoucherId();

    case TITLE:
      return getTitle();

    case CODE:
      return getCode();

    case IMAGE_URL:
      return getImageUrl();

    case PUBLIC_ID:
      return getPublicId();

    case BODY:
      return getBody();

    case DISCOUNT_PERCENT:
      return getDiscountPercent();

    case MAX_DISCOUNT:
      return getMaxDiscount();

    case START_DATE:
      return getStartDate();

    case END_DATE:
      return getEndDate();

    case CREATED_AT:
      return getCreatedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VOUCHER_ID:
      return isSetVoucherId();
    case TITLE:
      return isSetTitle();
    case CODE:
      return isSetCode();
    case IMAGE_URL:
      return isSetImageUrl();
    case PUBLIC_ID:
      return isSetPublicId();
    case BODY:
      return isSetBody();
    case DISCOUNT_PERCENT:
      return isSetDiscountPercent();
    case MAX_DISCOUNT:
      return isSetMaxDiscount();
    case START_DATE:
      return isSetStartDate();
    case END_DATE:
      return isSetEndDate();
    case CREATED_AT:
      return isSetCreatedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TVoucher)
      return this.equals((TVoucher)that);
    return false;
  }

  public boolean equals(TVoucher that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_voucherId = true && this.isSetVoucherId();
    boolean that_present_voucherId = true && that.isSetVoucherId();
    if (this_present_voucherId || that_present_voucherId) {
      if (!(this_present_voucherId && that_present_voucherId))
        return false;
      if (this.voucherId != that.voucherId)
        return false;
    }

    boolean this_present_title = true && this.isSetTitle();
    boolean that_present_title = true && that.isSetTitle();
    if (this_present_title || that_present_title) {
      if (!(this_present_title && that_present_title))
        return false;
      if (!this.title.equals(that.title))
        return false;
    }

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (!this.code.equals(that.code))
        return false;
    }

    boolean this_present_imageUrl = true && this.isSetImageUrl();
    boolean that_present_imageUrl = true && that.isSetImageUrl();
    if (this_present_imageUrl || that_present_imageUrl) {
      if (!(this_present_imageUrl && that_present_imageUrl))
        return false;
      if (!this.imageUrl.equals(that.imageUrl))
        return false;
    }

    boolean this_present_publicId = true && this.isSetPublicId();
    boolean that_present_publicId = true && that.isSetPublicId();
    if (this_present_publicId || that_present_publicId) {
      if (!(this_present_publicId && that_present_publicId))
        return false;
      if (!this.publicId.equals(that.publicId))
        return false;
    }

    boolean this_present_body = true && this.isSetBody();
    boolean that_present_body = true && that.isSetBody();
    if (this_present_body || that_present_body) {
      if (!(this_present_body && that_present_body))
        return false;
      if (!this.body.equals(that.body))
        return false;
    }

    boolean this_present_discountPercent = true && this.isSetDiscountPercent();
    boolean that_present_discountPercent = true && that.isSetDiscountPercent();
    if (this_present_discountPercent || that_present_discountPercent) {
      if (!(this_present_discountPercent && that_present_discountPercent))
        return false;
      if (this.discountPercent != that.discountPercent)
        return false;
    }

    boolean this_present_maxDiscount = true && this.isSetMaxDiscount();
    boolean that_present_maxDiscount = true && that.isSetMaxDiscount();
    if (this_present_maxDiscount || that_present_maxDiscount) {
      if (!(this_present_maxDiscount && that_present_maxDiscount))
        return false;
      if (this.maxDiscount != that.maxDiscount)
        return false;
    }

    boolean this_present_startDate = true && this.isSetStartDate();
    boolean that_present_startDate = true && that.isSetStartDate();
    if (this_present_startDate || that_present_startDate) {
      if (!(this_present_startDate && that_present_startDate))
        return false;
      if (this.startDate != that.startDate)
        return false;
    }

    boolean this_present_endDate = true && this.isSetEndDate();
    boolean that_present_endDate = true && that.isSetEndDate();
    if (this_present_endDate || that_present_endDate) {
      if (!(this_present_endDate && that_present_endDate))
        return false;
      if (this.endDate != that.endDate)
        return false;
    }

    boolean this_present_createdAt = true && this.isSetCreatedAt();
    boolean that_present_createdAt = true && that.isSetCreatedAt();
    if (this_present_createdAt || that_present_createdAt) {
      if (!(this_present_createdAt && that_present_createdAt))
        return false;
      if (this.createdAt != that.createdAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetVoucherId()) ? 131071 : 524287);
    if (isSetVoucherId())
      hashCode = hashCode * 8191 + voucherId;

    hashCode = hashCode * 8191 + ((isSetTitle()) ? 131071 : 524287);
    if (isSetTitle())
      hashCode = hashCode * 8191 + title.hashCode();

    hashCode = hashCode * 8191 + ((isSetCode()) ? 131071 : 524287);
    if (isSetCode())
      hashCode = hashCode * 8191 + code.hashCode();

    hashCode = hashCode * 8191 + ((isSetImageUrl()) ? 131071 : 524287);
    if (isSetImageUrl())
      hashCode = hashCode * 8191 + imageUrl.hashCode();

    hashCode = hashCode * 8191 + ((isSetPublicId()) ? 131071 : 524287);
    if (isSetPublicId())
      hashCode = hashCode * 8191 + publicId.hashCode();

    hashCode = hashCode * 8191 + ((isSetBody()) ? 131071 : 524287);
    if (isSetBody())
      hashCode = hashCode * 8191 + body.hashCode();

    hashCode = hashCode * 8191 + ((isSetDiscountPercent()) ? 131071 : 524287);
    if (isSetDiscountPercent())
      hashCode = hashCode * 8191 + discountPercent;

    hashCode = hashCode * 8191 + ((isSetMaxDiscount()) ? 131071 : 524287);
    if (isSetMaxDiscount())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(maxDiscount);

    hashCode = hashCode * 8191 + ((isSetStartDate()) ? 131071 : 524287);
    if (isSetStartDate())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startDate);

    hashCode = hashCode * 8191 + ((isSetEndDate()) ? 131071 : 524287);
    if (isSetEndDate())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endDate);

    hashCode = hashCode * 8191 + ((isSetCreatedAt()) ? 131071 : 524287);
    if (isSetCreatedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createdAt);

    return hashCode;
  }

  @Override
  public int compareTo(TVoucher other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetVoucherId()).compareTo(other.isSetVoucherId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVoucherId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.voucherId, other.voucherId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTitle()).compareTo(other.isSetTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title, other.title);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetImageUrl()).compareTo(other.isSetImageUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImageUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imageUrl, other.imageUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPublicId()).compareTo(other.isSetPublicId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPublicId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.publicId, other.publicId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBody()).compareTo(other.isSetBody());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBody()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.body, other.body);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDiscountPercent()).compareTo(other.isSetDiscountPercent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDiscountPercent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.discountPercent, other.discountPercent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMaxDiscount()).compareTo(other.isSetMaxDiscount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxDiscount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxDiscount, other.maxDiscount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartDate()).compareTo(other.isSetStartDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startDate, other.startDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndDate()).compareTo(other.isSetEndDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endDate, other.endDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreatedAt()).compareTo(other.isSetCreatedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdAt, other.createdAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TVoucher(");
    boolean first = true;

    if (isSetVoucherId()) {
      sb.append("voucherId:");
      sb.append(this.voucherId);
      first = false;
    }
    if (isSetTitle()) {
      if (!first) sb.append(", ");
      sb.append("title:");
      if (this.title == null) {
        sb.append("null");
      } else {
        sb.append(this.title);
      }
      first = false;
    }
    if (isSetCode()) {
      if (!first) sb.append(", ");
      sb.append("code:");
      if (this.code == null) {
        sb.append("null");
      } else {
        sb.append(this.code);
      }
      first = false;
    }
    if (isSetImageUrl()) {
      if (!first) sb.append(", ");
      sb.append("imageUrl:");
      if (this.imageUrl == null) {
        sb.append("null");
      } else {
        sb.append(this.imageUrl);
      }
      first = false;
    }
    if (isSetPublicId()) {
      if (!first) sb.append(", ");
      sb.append("publicId:");
      if (this.publicId == null) {
        sb.append("null");
      } else {
        sb.append(this.publicId);
      }
      first = false;
    }
    if (isSetBody()) {
      if (!first) sb.append(", ");
      sb.append("body:");
      if (this.body == null) {
        sb.append("null");
      } else {
        sb.append(this.body);
      }
      first = false;
    }
    if (isSetDiscountPercent()) {
      if (!first) sb.append(", ");
      sb.append("discountPercent:");
      sb.append(this.discountPercent);
      first = false;
    }
    if (isSetMaxDiscount()) {
      if (!first) sb.append(", ");
      sb.append("maxDiscount:");
      sb.append(this.maxDiscount);
      first = false;
    }
    if (isSetStartDate()) {
      if (!first) sb.append(", ");
      sb.append("startDate:");
      sb.append(this.startDate);
      first = false;
    }
    if (isSetEndDate()) {
      if (!first) sb.append(", ");
      sb.append("endDate:");
      sb.append(this.endDate);
      first = false;
    }
    if (isSetCreatedAt()) {
      if (!first) sb.append(", ");
      sb.append("createdAt:");
      sb.append(this.createdAt);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TVoucherStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TVoucherStandardScheme getScheme() {
      return new TVoucherStandardScheme();
    }
  }

  private static class TVoucherStandardScheme extends org.apache.thrift.scheme.StandardScheme<TVoucher> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TVoucher struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VOUCHER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.voucherId = iprot.readI32();
              struct.setVoucherIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title = iprot.readString();
              struct.setTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.code = iprot.readString();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IMAGE_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imageUrl = iprot.readString();
              struct.setImageUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PUBLIC_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.publicId = iprot.readString();
              struct.setPublicIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // BODY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.body = iprot.readString();
              struct.setBodyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DISCOUNT_PERCENT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.discountPercent = iprot.readI32();
              struct.setDiscountPercentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // MAX_DISCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.maxDiscount = iprot.readI64();
              struct.setMaxDiscountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // START_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startDate = iprot.readI64();
              struct.setStartDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // END_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endDate = iprot.readI64();
              struct.setEndDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // CREATED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createdAt = iprot.readI64();
              struct.setCreatedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TVoucher struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetVoucherId()) {
        oprot.writeFieldBegin(VOUCHER_ID_FIELD_DESC);
        oprot.writeI32(struct.voucherId);
        oprot.writeFieldEnd();
      }
      if (struct.title != null) {
        if (struct.isSetTitle()) {
          oprot.writeFieldBegin(TITLE_FIELD_DESC);
          oprot.writeString(struct.title);
          oprot.writeFieldEnd();
        }
      }
      if (struct.code != null) {
        if (struct.isSetCode()) {
          oprot.writeFieldBegin(CODE_FIELD_DESC);
          oprot.writeString(struct.code);
          oprot.writeFieldEnd();
        }
      }
      if (struct.imageUrl != null) {
        if (struct.isSetImageUrl()) {
          oprot.writeFieldBegin(IMAGE_URL_FIELD_DESC);
          oprot.writeString(struct.imageUrl);
          oprot.writeFieldEnd();
        }
      }
      if (struct.publicId != null) {
        if (struct.isSetPublicId()) {
          oprot.writeFieldBegin(PUBLIC_ID_FIELD_DESC);
          oprot.writeString(struct.publicId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.body != null) {
        if (struct.isSetBody()) {
          oprot.writeFieldBegin(BODY_FIELD_DESC);
          oprot.writeString(struct.body);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetDiscountPercent()) {
        oprot.writeFieldBegin(DISCOUNT_PERCENT_FIELD_DESC);
        oprot.writeI32(struct.discountPercent);
        oprot.writeFieldEnd();
      }
      if (struct.isSetMaxDiscount()) {
        oprot.writeFieldBegin(MAX_DISCOUNT_FIELD_DESC);
        oprot.writeI64(struct.maxDiscount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetStartDate()) {
        oprot.writeFieldBegin(START_DATE_FIELD_DESC);
        oprot.writeI64(struct.startDate);
        oprot.writeFieldEnd();
      }
      if (struct.isSetEndDate()) {
        oprot.writeFieldBegin(END_DATE_FIELD_DESC);
        oprot.writeI64(struct.endDate);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeFieldBegin(CREATED_AT_FIELD_DESC);
        oprot.writeI64(struct.createdAt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TVoucherTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TVoucherTupleScheme getScheme() {
      return new TVoucherTupleScheme();
    }
  }

  private static class TVoucherTupleScheme extends org.apache.thrift.scheme.TupleScheme<TVoucher> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TVoucher struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVoucherId()) {
        optionals.set(0);
      }
      if (struct.isSetTitle()) {
        optionals.set(1);
      }
      if (struct.isSetCode()) {
        optionals.set(2);
      }
      if (struct.isSetImageUrl()) {
        optionals.set(3);
      }
      if (struct.isSetPublicId()) {
        optionals.set(4);
      }
      if (struct.isSetBody()) {
        optionals.set(5);
      }
      if (struct.isSetDiscountPercent()) {
        optionals.set(6);
      }
      if (struct.isSetMaxDiscount()) {
        optionals.set(7);
      }
      if (struct.isSetStartDate()) {
        optionals.set(8);
      }
      if (struct.isSetEndDate()) {
        optionals.set(9);
      }
      if (struct.isSetCreatedAt()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetVoucherId()) {
        oprot.writeI32(struct.voucherId);
      }
      if (struct.isSetTitle()) {
        oprot.writeString(struct.title);
      }
      if (struct.isSetCode()) {
        oprot.writeString(struct.code);
      }
      if (struct.isSetImageUrl()) {
        oprot.writeString(struct.imageUrl);
      }
      if (struct.isSetPublicId()) {
        oprot.writeString(struct.publicId);
      }
      if (struct.isSetBody()) {
        oprot.writeString(struct.body);
      }
      if (struct.isSetDiscountPercent()) {
        oprot.writeI32(struct.discountPercent);
      }
      if (struct.isSetMaxDiscount()) {
        oprot.writeI64(struct.maxDiscount);
      }
      if (struct.isSetStartDate()) {
        oprot.writeI64(struct.startDate);
      }
      if (struct.isSetEndDate()) {
        oprot.writeI64(struct.endDate);
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeI64(struct.createdAt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TVoucher struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.voucherId = iprot.readI32();
        struct.setVoucherIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.title = iprot.readString();
        struct.setTitleIsSet(true);
      }
      if (incoming.get(2)) {
        struct.code = iprot.readString();
        struct.setCodeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.imageUrl = iprot.readString();
        struct.setImageUrlIsSet(true);
      }
      if (incoming.get(4)) {
        struct.publicId = iprot.readString();
        struct.setPublicIdIsSet(true);
      }
      if (incoming.get(5)) {
        struct.body = iprot.readString();
        struct.setBodyIsSet(true);
      }
      if (incoming.get(6)) {
        struct.discountPercent = iprot.readI32();
        struct.setDiscountPercentIsSet(true);
      }
      if (incoming.get(7)) {
        struct.maxDiscount = iprot.readI64();
        struct.setMaxDiscountIsSet(true);
      }
      if (incoming.get(8)) {
        struct.startDate = iprot.readI64();
        struct.setStartDateIsSet(true);
      }
      if (incoming.get(9)) {
        struct.endDate = iprot.readI64();
        struct.setEndDateIsSet(true);
      }
      if (incoming.get(10)) {
        struct.createdAt = iprot.readI64();
        struct.setCreatedAtIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

