/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2026-10-07")
public class TVoucherRequest implements org.apache.thrift.TBase<TVoucherRequest, TVoucherRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TVoucherRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TVoucherRequest");

  private static final org.apache.thrift.protocol.TField TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("title", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("body", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DISCOUNT_PERCENT_FIELD_DESC = new org.apache.thrift.protocol.TField("discountPercent", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField MAX_DISCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("maxDiscount", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField START_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("startDate", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField END_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("endDate", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField IMAGE_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("imageUrl", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField PUBLIC_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("publicId", org.apache.thrift.protocol.TType.STRING, (short)9);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TVoucherRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TVoucherRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String title; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String code; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String body; // required
  public int discountPercent; // required
  public long maxDiscount; // required
  public long startDate; // required
  public long endDate; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String imageUrl; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String publicId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TITLE((short)1, "title"),
    CODE((short)2, "code"),
    BODY((short)3, "body"),
    DISCOUNT_PERCENT((short)4, "discountPercent"),
    MAX_DISCOUNT((short)5, "maxDiscount"),
    START_DATE((short)6, "startDate"),
    END_DATE((short)7, "endDate"),
    IMAGE_URL((short)8, "imageUrl"),
    PUBLIC_ID((short)9, "publicId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TITLE
          return TITLE;
        case 2: // CODE
          return CODE;
        case 3: // BODY
          return BODY;
        case 4: // DISCOUNT_PERCENT
          return DISCOUNT_PERCENT;
        case 5: // MAX_DISCOUNT
          return MAX_DISCOUNT;
        case 6: // START_DATE
          return START_DATE;
        case 7: // END_DATE
          return END_DATE;
        case 8: // IMAGE_URL
          return IMAGE_URL;
        case 9: // PUBLIC_ID
          return PUBLIC_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DISCOUNTPERCENT_ISSET_ID = 0;
  private static final int __MAXDISCOUNT_ISSET_ID = 1;
  private static final int __STARTDATE_ISSET_ID = 2;
  private static final int __ENDDATE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TITLE, new org.apache.thrift.meta_data.FieldMetaData("title", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BODY, new org.apache.thrift.meta_data.FieldMetaData("body", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISCOUNT_PERCENT, new org.apache.thrift.meta_data.FieldMetaData("discountPercent", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAX_DISCOUNT, new org.apache.thrift.meta_data.FieldMetaData("maxDiscount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.START_DATE, new org.apache.thrift.meta_data.FieldMetaData("startDate", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_DATE, new org.apache.thrift.meta_data.FieldMetaData("endDate", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IMAGE_URL, new org.apache.thrift.meta_data.FieldMetaData("imageUrl", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PUBLIC_ID, new org.apache.thrift.meta_data.FieldMetaData("publicId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TVoucherRequest.class, metaDataMap);
  }

  public TVoucherRequest() {
  }

  public TVoucherRequest(
    java.lang.String title,
    java.lang.String code,
    java.lang.String body,
    int discountPercent,
    long maxDiscount,
    long startDate,
    long endDate,
    java.lang.String imageUrl,
    java.lang.String publicId)
  {
    this();
    this.title = title;
    this.code = code;
    this.body = body;
    this.discountPercent = discountPercent;
    setDiscountPercentIsSet(true);
    this.maxDiscount = maxDiscount;
    setMaxDiscountIsSet(true);
    this.startDate = startDate;
    setStartDateIsSet(true);
    this.endDate = endDate;
    setEndDateIsSet(true);
    this.imageUrl = imageUrl;
    this.publicId = publicId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TVoucherRequest(TVoucherRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTitle()) {
      this.title = other.title;
    }
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetBody()) {
      this.body = other.body;
    }
    this.discountPercent = other.discountPercent;
    this.maxDiscount = other.maxDiscount;
    this.startDate = other.startDate;
    this.endDate = other.endDate;
    if (other.isSetImageUrl()) {
      this.imageUrl = other.imageUrl;
    }
    if (other.isSetPublicId()) {
      this.publicId = other.publicId;
    }
  }

  public TVoucherRequest deepCopy() {
    return new TVoucherRequest(this);
  }

  @Override
  public void clear() {
    this.title = null;
    this.code = null;
    this.body = null;
    setDiscountPercentIsSet(false);
    this.discountPercent = 0;
    setMaxDiscountIsSet(false);
    this.maxDiscount = 0;
    setStartDateIsSet(false);
    this.startDate = 0;
    setEndDateIsSet(false);
    this.endDate = 0;
    this.imageUrl = null;
    this.publicId = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTitle() {
    return this.title;
  }

  public TVoucherRequest setTitle(@org.apache.thrift.annotation.Nullable java.lang.String title) {
    this.title = title;
    return this;
  }

  public void unsetTitle() {
    this.title = null;
  }

  /** Returns true if field title is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle() {
    return this.title != null;
  }

  public void setTitleIsSet(boolean value) {
    if (!value) {
      this.title = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCode() {
    return this.code;
  }

  public TVoucherRequest setCode(@org.apache.thrift.annotation.Nullable java.lang.String code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBody() {
    return this.body;
  }

  public TVoucherRequest setBody(@org.apache.thrift.annotation.Nullable java.lang.String body) {
    this.body = body;
    return this;
  }

  public void unsetBody() {
    this.body = null;
  }

  /** Returns true if field body is set (has been assigned a value) and false otherwise */
  public boolean isSetBody() {
    return this.body != null;
  }

  public void setBodyIsSet(boolean value) {
    if (!value) {
      this.body = null;
    }
  }

  public int getDiscountPercent() {
    return this.discountPercent;
  }

  public TVoucherRequest setDiscountPercent(int discountPercent) {
    this.discountPercent = discountPercent;
    setDiscountPercentIsSet(true);
    return this;
  }

  public void unsetDiscountPercent() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID);
  }

  /** Returns true if field discountPercent is set (has been assigned a value) and false otherwise */
  public boolean isSetDiscountPercent() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID);
  }

  public void setDiscountPercentIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISCOUNTPERCENT_ISSET_ID, value);
  }

  public long getMaxDiscount() {
    return this.maxDiscount;
  }

  public TVoucherRequest setMaxDiscount(long maxDiscount) {
    this.maxDiscount = maxDiscount;
    setMaxDiscountIsSet(true);
    return this;
  }

  public void unsetMaxDiscount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID);
  }

  /** Returns true if field maxDiscount is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxDiscount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID);
  }

  public void setMaxDiscountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXDISCOUNT_ISSET_ID, value);
  }

  public long getStartDate() {
    return this.startDate;
  }

  public TVoucherRequest setStartDate(long startDate) {
    this.startDate = startDate;
    setStartDateIsSet(true);
    return this;
  }

  public void unsetStartDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  /** Returns true if field startDate is set (has been assigned a value) and false otherwise */
  public boolean isSetStartDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTDATE_ISSET_ID);
  }

  public void setStartDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTDATE_ISSET_ID, value);
  }

  public long getEndDate() {
    return this.endDate;
  }

  public TVoucherRequest setEndDate(long endDate) {
    this.endDate = endDate;
    setEndDateIsSet(true);
    return this;
  }

  public void unsetEndDate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  /** Returns true if field endDate is set (has been assigned a value) and false otherwise */
  public boolean isSetEndDate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDDATE_ISSET_ID);
  }

  public void setEndDateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDDATE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getImageUrl() {
    return this.imageUrl;
  }

  public TVoucherRequest setImageUrl(@org.apache.thrift.annotation.Nullable java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  public void unsetImageUrl() {
    this.imageUrl = null;
  }

  /** Returns true if field imageUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetImageUrl() {
    return this.imageUrl != null;
  }

  public void setImageUrlIsSet(boolean value) {
    if (!value) {
      this.imageUrl = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPublicId() {
    return this.publicId;
  }

  public TVoucherRequest setPublicId(@org.apache.thrift.annotation.Nullable java.lang.String publicId) {
    this.publicId = publicId;
    return this;
  }

  public void unsetPublicId() {
    this.publicId = null;
  }

  /** Returns true if field publicId is set (has been assigned a value) and false otherwise */
  public boolean isSetPublicId() {
    return this.publicId != null;
  }

  public void setPublicIdIsSet(boolean value) {
    if (!value) {
      this.publicId = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TITLE:
      if (value == null) {
        unsetTitle();
      } else {
        setTitle((java.lang.String)value);
      }
      break;

    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((java.lang.String)value);
      }
      break;

    case BODY:
      if (value == null) {
        unsetBody();
      } else {
        setBody((java.lang.String)value);
      }
      break;

    case DISCOUNT_PERCENT:
      if (value == null) {
        unsetDiscountPercent();
      } else {
        setDiscountPercent((java.lang.Integer)value);
      }
      break;

    case MAX_DISCOUNT:
      if (value == null) {
        unsetMaxDiscount();
      } else {
        setMaxDiscount((java.lang.Long)value);
      }
      break;

    case START_DATE:
      if (value == null) {
        unsetStartDate();
      } else {
        setStartDate((java.lang.Long)value);
      }
      break;

    case END_DATE:
      if (value == null) {
        unsetEndDate();
      } else {
        setEndDate((java.lang.Long)value);
      }
      break;

    case IMAGE_URL:
      if (value == null) {
        unsetImageUrl();
      } else {
        setImageUrl((java.lang.String)value);
      }
      break;

    case PUBLIC_ID:
      if (value == null) {
        unsetPublicId();
      } else {
        setPublicId((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TITLE:
      return getTitle();

    case CODE:
      return getCode();

    case BODY:
      return getBody();

    case DISCOUNT_PERCENT:
      return getDiscountPercent();

    case MAX_DISCOUNT:
      return getMaxDiscount();

    case START_DATE:
      return getStartDate();

    case END_DATE:
      return getEndDate();

    case IMAGE_URL:
      return getImageUrl();

    case PUBLIC_ID:
      return getPublicId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TITLE:
      return isSetTitle();
    case CODE:
      return isSetCode();
    case BODY:
      return isSetBody();
    case DISCOUNT_PERCENT:
      return isSetDiscountPercent();
    case MAX_DISCOUNT:
      return isSetMaxDiscount();
    case START_DATE:
      return isSetStartDate();
    case END_DATE:
      return isSetEndDate();
    case IMAGE_URL:
      return isSetImageUrl();
    case PUBLIC_ID:
      return isSetPublicId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TVoucherRequest)
      return this.equals((TVoucherRequest)that);
    return false;
  }

  public boolean equals(TVoucherRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_title = true && this.isSetTitle();
    boolean that_present_title = true && that.isSetTitle();
    if (this_present_title || that_present_title) {
      if (!(this_present_title && that_present_title))
        return false;
      if (!this.title.equals(that.title))
        return false;
    }

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (!this.code.equals(that.code))
        return false;
    }

    boolean this_present_body = true && this.isSetBody();
    boolean that_present_body = true && that.isSetBody();
    if (this_present_body || that_present_body) {
      if (!(this_present_body && that_present_body))
        return false;
      if (!this.body.equals(that.body))
        return false;
    }

    boolean this_present_discountPercent = true;
    boolean that_present_discountPercent = true;
    if (this_present_discountPercent || that_present_discountPercent) {
      if (!(this_present_discountPercent && that_present_discountPercent))
        return false;
      if (this.discountPercent != that.discountPercent)
        return false;
    }

    boolean this_present_maxDiscount = true;
    boolean that_present_maxDiscount = true;
    if (this_present_maxDiscount || that_present_maxDiscount) {
      if (!(this_present_maxDiscount && that_present_maxDiscount))
        return false;
      if (this.maxDiscount != that.maxDiscount)
        return false;
    }

    boolean this_present_startDate = true;
    boolean that_present_startDate = true;
    if (this_present_startDate || that_present_startDate) {
      if (!(this_present_startDate && that_present_startDate))
        return false;
      if (this.startDate != that.startDate)
        return false;
    }

    boolean this_present_endDate = true;
    boolean that_present_endDate = true;
    if (this_present_endDate || that_present_endDate) {
      if (!(this_present_endDate && that_present_endDate))
        return false;
      if (this.endDate != that.endDate)
        return false;
    }

    boolean this_present_imageUrl = true && this.isSetImageUrl();
    boolean that_present_imageUrl = true && that.isSetImageUrl();
    if (this_present_imageUrl || that_present_imageUrl) {
      if (!(this_present_imageUrl && that_present_imageUrl))
        return false;
      if (!this.imageUrl.equals(that.imageUrl))
        return false;
    }

    boolean this_present_publicId = true && this.isSetPublicId();
    boolean that_present_publicId = true && that.isSetPublicId();
    if (this_present_publicId || that_present_publicId) {
      if (!(this_present_publicId && that_present_publicId))
        return false;
      if (!this.publicId.equals(that.publicId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTitle()) ? 131071 : 524287);
    if (isSetTitle())
      hashCode = hashCode * 8191 + title.hashCode();

    hashCode = hashCode * 8191 + ((isSetCode()) ? 131071 : 524287);
    if (isSetCode())
      hashCode = hashCode * 8191 + code.hashCode();

    hashCode = hashCode * 8191 + ((isSetBody()) ? 131071 : 524287);
    if (isSetBody())
      hashCode = hashCode * 8191 + body.hashCode();

    hashCode = hashCode * 8191 + discountPercent;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(maxDiscount);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startDate);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endDate);

    hashCode = hashCode * 8191 + ((isSetImageUrl()) ? 131071 : 524287);
    if (isSetImageUrl())
      hashCode = hashCode * 8191 + imageUrl.hashCode();

    hashCode = hashCode * 8191 + ((isSetPublicId()) ? 131071 : 524287);
    if (isSetPublicId())
      hashCode = hashCode * 8191 + publicId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TVoucherRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTitle()).compareTo(other.isSetTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title, other.title);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBody()).compareTo(other.isSetBody());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBody()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.body, other.body);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDiscountPercent()).compareTo(other.isSetDiscountPercent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDiscountPercent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.discountPercent, other.discountPercent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMaxDiscount()).compareTo(other.isSetMaxDiscount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxDiscount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxDiscount, other.maxDiscount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartDate()).compareTo(other.isSetStartDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startDate, other.startDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndDate()).compareTo(other.isSetEndDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endDate, other.endDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetImageUrl()).compareTo(other.isSetImageUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImageUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imageUrl, other.imageUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPublicId()).compareTo(other.isSetPublicId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPublicId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.publicId, other.publicId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TVoucherRequest(");
    boolean first = true;

    sb.append("title:");
    if (this.title == null) {
      sb.append("null");
    } else {
      sb.append(this.title);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("code:");
    if (this.code == null) {
      sb.append("null");
    } else {
      sb.append(this.code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("body:");
    if (this.body == null) {
      sb.append("null");
    } else {
      sb.append(this.body);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("discountPercent:");
    sb.append(this.discountPercent);
    first = false;
    if (!first) sb.append(", ");
    sb.append("maxDiscount:");
    sb.append(this.maxDiscount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("startDate:");
    sb.append(this.startDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endDate:");
    sb.append(this.endDate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("imageUrl:");
    if (this.imageUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.imageUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("publicId:");
    if (this.publicId == null) {
      sb.append("null");
    } else {
      sb.append(this.publicId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (title == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'title' was not present! Struct: " + toString());
    }
    if (code == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'code' was not present! Struct: " + toString());
    }
    if (body == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'body' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'discountPercent' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'maxDiscount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'startDate' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'endDate' because it's a primitive and you chose the non-beans generator.
    if (imageUrl == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'imageUrl' was not present! Struct: " + toString());
    }
    if (publicId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'publicId' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TVoucherRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TVoucherRequestStandardScheme getScheme() {
      return new TVoucherRequestStandardScheme();
    }
  }

  private static class TVoucherRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TVoucherRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TVoucherRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title = iprot.readString();
              struct.setTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.code = iprot.readString();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BODY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.body = iprot.readString();
              struct.setBodyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DISCOUNT_PERCENT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.discountPercent = iprot.readI32();
              struct.setDiscountPercentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MAX_DISCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.maxDiscount = iprot.readI64();
              struct.setMaxDiscountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // START_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startDate = iprot.readI64();
              struct.setStartDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // END_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endDate = iprot.readI64();
              struct.setEndDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IMAGE_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imageUrl = iprot.readString();
              struct.setImageUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PUBLIC_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.publicId = iprot.readString();
              struct.setPublicIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetDiscountPercent()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'discountPercent' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetMaxDiscount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxDiscount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStartDate()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'startDate' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetEndDate()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'endDate' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TVoucherRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.title != null) {
        oprot.writeFieldBegin(TITLE_FIELD_DESC);
        oprot.writeString(struct.title);
        oprot.writeFieldEnd();
      }
      if (struct.code != null) {
        oprot.writeFieldBegin(CODE_FIELD_DESC);
        oprot.writeString(struct.code);
        oprot.writeFieldEnd();
      }
      if (struct.body != null) {
        oprot.writeFieldBegin(BODY_FIELD_DESC);
        oprot.writeString(struct.body);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DISCOUNT_PERCENT_FIELD_DESC);
      oprot.writeI32(struct.discountPercent);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAX_DISCOUNT_FIELD_DESC);
      oprot.writeI64(struct.maxDiscount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(START_DATE_FIELD_DESC);
      oprot.writeI64(struct.startDate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(END_DATE_FIELD_DESC);
      oprot.writeI64(struct.endDate);
      oprot.writeFieldEnd();
      if (struct.imageUrl != null) {
        oprot.writeFieldBegin(IMAGE_URL_FIELD_DESC);
        oprot.writeString(struct.imageUrl);
        oprot.writeFieldEnd();
      }
      if (struct.publicId != null) {
        oprot.writeFieldBegin(PUBLIC_ID_FIELD_DESC);
        oprot.writeString(struct.publicId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TVoucherRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TVoucherRequestTupleScheme getScheme() {
      return new TVoucherRequestTupleScheme();
    }
  }

  private static class TVoucherRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TVoucherRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TVoucherRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.title);
      oprot.writeString(struct.code);
      oprot.writeString(struct.body);
      oprot.writeI32(struct.discountPercent);
      oprot.writeI64(struct.maxDiscount);
      oprot.writeI64(struct.startDate);
      oprot.writeI64(struct.endDate);
      oprot.writeString(struct.imageUrl);
      oprot.writeString(struct.publicId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TVoucherRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.title = iprot.readString();
      struct.setTitleIsSet(true);
      struct.code = iprot.readString();
      struct.setCodeIsSet(true);
      struct.body = iprot.readString();
      struct.setBodyIsSet(true);
      struct.discountPercent = iprot.readI32();
      struct.setDiscountPercentIsSet(true);
      struct.maxDiscount = iprot.readI64();
      struct.setMaxDiscountIsSet(true);
      struct.startDate = iprot.readI64();
      struct.setStartDateIsSet(true);
      struct.endDate = iprot.readI64();
      struct.setEndDateIsSet(true);
      struct.imageUrl = iprot.readString();
      struct.setImageUrlIsSet(true);
      struct.publicId = iprot.readString();
      struct.setPublicIdIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

